import { useEffect, useState, type FormEvent } from "react";
import { ArrowLeft, Pencil, Plus } from "lucide-react";
import { api } from "../../../shared/api/client";
import { Button, DataTable } from "../../../shared/ui";

type Customer = { id: string; name: string };
type ProjectStatus = "LEAD" | "ACTIVE" | "ON_HOLD" | "COMPLETED" | "CANCELLED";
type Project = {
  id: string; customerId: string; customerName: string; name: string; location?: string; projectType?: string;
  description?: string; estimatedValue?: number; startDate?: string; requiredDeliveryDate?: string;
  assignedSalesAgent?: string; status: ProjectStatus; notes?: string;
};
type ProjectFormData = Omit<Project, "id" | "customerName">;
type ProjectPageResponse = { content: Project[] };

const field = "mt-1 h-10 w-full rounded-md border border-[#d8ccc4] bg-white px-3 text-sm outline-none focus:border-[#110703]";
const textarea = "mt-1 min-h-24 w-full rounded-md border border-[#d8ccc4] bg-white p-3 text-sm outline-none focus:border-[#110703]";
const statuses: ProjectStatus[] = ["LEAD", "ACTIVE", "ON_HOLD", "COMPLETED", "CANCELLED"];
const emptyForm = (): ProjectFormData => ({ customerId: "", name: "", location: "", projectType: "", description: "", estimatedValue: undefined, startDate: "", requiredDeliveryDate: "", assignedSalesAgent: "", status: "LEAD", notes: "" });
function toPayload(form: ProjectFormData) { return { ...form, location: form.location || null, projectType: form.projectType || null, description: form.description || null, estimatedValue: form.estimatedValue ?? null, startDate: form.startDate || null, requiredDeliveryDate: form.requiredDeliveryDate || null, assignedSalesAgent: form.assignedSalesAgent || null, notes: form.notes || null }; }
function dateValue(value?: string) { return value?.slice(0, 10) ?? ""; }
function money(value?: number) { return value == null ? "—" : new Intl.NumberFormat("en-US", { style: "currency", currency: "MAD" }).format(value); }
function statusLabel(value: ProjectStatus) { return value.replaceAll("_", " "); }

export function ProjectsPage() {
  const [projects, setProjects] = useState<Project[]>([]);
  const [customers, setCustomers] = useState<Customer[]>([]);
  const [screen, setScreen] = useState<"list" | "create" | "detail" | "edit">("list");
  const [detail, setDetail] = useState<Project | null>(null);
  const [search, setSearch] = useState("");
  const [status, setStatus] = useState<"" | ProjectStatus>("");
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  async function load() { const query = new URLSearchParams({ size: "100" }); if (search.trim()) query.set("search", search.trim()); if (status) query.set("status", status); setLoading(true); setError(""); try { setProjects((await api<ProjectPageResponse>(`/projects?${query}`)).content); } catch (reason) { setError(reason instanceof Error ? reason.message : "Projects could not be loaded."); } finally { setLoading(false); } }
  useEffect(() => { void load(); }, [search, status]);
  useEffect(() => { void api<{ content: Customer[] }>("/customers?size=100").then((page) => setCustomers(page.content)); }, []);
  async function openDetail(id: string) { setDetail(await api<Project>(`/projects/${id}`)); setScreen("detail"); }
  if (screen === "create" || (screen === "edit" && detail)) return <ProjectForm title={screen === "create" ? "New project" : `Edit ${detail!.name}`} customers={customers} initial={screen === "edit" ? detail! : undefined} back={() => setScreen(screen === "edit" ? "detail" : "list")} saved={async (project) => { setDetail(project); await load(); setScreen("detail"); }} />;
  if (screen === "detail" && detail) return <ProjectDetail project={detail} back={() => { setScreen("list"); void load(); }} edit={() => setScreen("edit")} />;
  return <section className="mx-auto max-w-6xl px-4 py-7 sm:px-7">
    <header className="flex flex-col gap-4 border-b border-[#dfd4cd] pb-6 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-[10px] font-bold tracking-[.18em] text-[#765847]">PROJECT PORTFOLIO</p><h1 className="mt-2 font-serif text-4xl">Projects</h1></div><Button onClick={() => setScreen("create")}><Plus size={16} />Create project</Button></header>
    <div className="mt-5 flex flex-col gap-3 sm:flex-row"><input value={search} onChange={(event) => setSearch(event.target.value)} className={field} placeholder="Search projects" aria-label="Search projects" /><select value={status} onChange={(event) => setStatus(event.target.value as "" | ProjectStatus)} className={`${field} sm:max-w-48`} aria-label="Filter by status"><option value="">All statuses</option>{statuses.map((item) => <option key={item} value={item}>{statusLabel(item)}</option>)}</select></div>
    <div className="mt-5 overflow-hidden rounded-xl border border-[#e3d8d1] bg-white">{error ? <div className="px-5 py-10 text-center text-sm text-red-700"><p>{error}</p><Button className="mt-4" size="sm" variant="outline" onClick={() => void load()}>Try again</Button></div> : loading ? <p className="px-5 py-12 text-center text-sm text-[#786961]">Loading projects…</p> : <><DataTable><thead className="bg-[#faf7f5] text-xs"><tr><th className="px-5 py-3">Project</th><th className="px-5 py-3">Customer</th><th className="px-5 py-3">Type</th><th className="px-5 py-3">Value</th><th className="px-5 py-3">Status</th></tr></thead><tbody>{projects.map((item) => <tr key={item.id} onClick={() => void openDetail(item.id)} className="cursor-pointer border-t border-[#f0e8e4] hover:bg-[#fdfaf8]"><td className="px-5 py-4 font-semibold">{item.name}</td><td className="px-5 py-4 text-sm">{item.customerName}</td><td className="px-5 py-4 text-sm">{item.projectType ?? "—"}</td><td className="px-5 py-4 text-sm">{money(item.estimatedValue)}</td><td className="px-5 py-4 text-xs font-semibold tracking-wide">{statusLabel(item.status)}</td></tr>)}</tbody></DataTable>{!projects.length && <p className="px-5 py-12 text-center text-sm text-[#786961]">No projects match this view.</p>}</>}</div>
  </section>;
}

function ProjectForm({ title, customers, initial, back, saved }: { title: string; customers: Customer[]; initial?: Project; back: () => void; saved: (project: Project) => Promise<void> }) {
  const [form, setForm] = useState<ProjectFormData>(() => initial ? { ...initial, startDate: dateValue(initial.startDate), requiredDeliveryDate: dateValue(initial.requiredDeliveryDate) } : emptyForm());
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState("");
  const change = <K extends keyof ProjectFormData>(key: K, value: ProjectFormData[K]) => setForm((current) => ({ ...current, [key]: value }));
  async function submit(event: FormEvent) { event.preventDefault(); setSaving(true); setError(""); try { const project = await api<Project>(initial ? `/projects/${initial.id}` : "/projects", { method: initial ? "PUT" : "POST", body: JSON.stringify(toPayload(form)) }); await saved(project); } catch (reason) { setError(reason instanceof Error ? reason.message : "The project could not be saved."); } finally { setSaving(false); } }
  return <section className="mx-auto max-w-4xl px-4 py-7 sm:px-7"><button onClick={back} className="inline-flex items-center gap-2 text-sm text-[#4b3328]"><ArrowLeft size={16} />Projects</button><form onSubmit={submit} className="mt-5 rounded-xl border border-[#e3d8d1] bg-white p-5 sm:p-7"><h1 className="font-serif text-3xl">{title}</h1><p className="mt-2 text-sm text-[#786961]">Keep the commercial, delivery, and ownership information together.</p>
    <div className="mt-6 grid gap-4 md:grid-cols-2"><label className="text-sm font-medium">Customer<select required value={form.customerId} onChange={(event) => change("customerId", event.target.value)} className={field}><option value="">Select a customer</option>{customers.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label className="text-sm font-medium">Project name<input required value={form.name} onChange={(event) => change("name", event.target.value)} className={field} /></label><label className="text-sm font-medium">Location<input value={form.location ?? ""} onChange={(event) => change("location", event.target.value)} className={field} /></label><label className="text-sm font-medium">Project type<input value={form.projectType ?? ""} onChange={(event) => change("projectType", event.target.value)} className={field} placeholder="Residential, hospitality…" /></label><label className="text-sm font-medium">Estimated value (MAD)<input min="0" step="0.01" type="number" value={form.estimatedValue ?? ""} onChange={(event) => change("estimatedValue", event.target.value === "" ? undefined : Number(event.target.value))} className={field} /></label><label className="text-sm font-medium">Status<select value={form.status} onChange={(event) => change("status", event.target.value as ProjectStatus)} className={field}>{statuses.map((item) => <option key={item} value={item}>{statusLabel(item)}</option>)}</select></label><label className="text-sm font-medium">Start date<input type="date" value={form.startDate ?? ""} onChange={(event) => change("startDate", event.target.value)} className={field} /></label><label className="text-sm font-medium">Required delivery date<input type="date" value={form.requiredDeliveryDate ?? ""} onChange={(event) => change("requiredDeliveryDate", event.target.value)} className={field} /></label><label className="text-sm font-medium md:col-span-2">Assigned sales agent<input value={form.assignedSalesAgent ?? ""} onChange={(event) => change("assignedSalesAgent", event.target.value)} className={field} /></label><label className="text-sm font-medium md:col-span-2">Description<textarea value={form.description ?? ""} onChange={(event) => change("description", event.target.value)} className={textarea} /></label><label className="text-sm font-medium md:col-span-2">Internal notes<textarea value={form.notes ?? ""} onChange={(event) => change("notes", event.target.value)} className={textarea} /></label></div>{error && <p role="alert" className="mt-4 text-sm text-red-700">{error}</p>}<div className="mt-6 flex justify-end gap-2"><Button type="button" variant="outline" onClick={back}>Cancel</Button><Button type="submit" loading={saving}>{initial ? "Save changes" : "Create project"}</Button></div>
  </form></section>;
}

function ProjectDetail({ project, back, edit }: { project: Project; back: () => void; edit: () => void }) {
  const [tab, setTab] = useState("Overview"); const tabs = ["Overview", "Materials", "RFQs", "Quotations", "Orders", "Deliveries", "Documents"];
  return <section className="mx-auto max-w-5xl px-4 py-7 sm:px-7"><button onClick={back} className="inline-flex items-center gap-2 text-sm text-[#4b3328]"><ArrowLeft size={16} />Projects</button><div className="mt-5 flex flex-col justify-between gap-3 sm:flex-row sm:items-start"><div><p className="text-[10px] font-bold tracking-[.18em] text-[#765847]">{statusLabel(project.status)}</p><h1 className="mt-2 font-serif text-4xl">{project.name}</h1><p className="mt-2 text-sm text-[#786961]">{project.customerName}{project.location ? ` · ${project.location}` : ""}</p></div><Button variant="outline" onClick={edit}><Pencil size={16} />Edit project</Button></div><div className="mt-6 flex flex-wrap gap-2 border-b border-[#e3d8d1]">{tabs.map((item) => <button key={item} onClick={() => setTab(item)} className={`px-3 py-2 text-sm ${tab === item ? "border-b-2 border-[#110703] font-semibold" : "text-[#786961]"}`}>{item}</button>)}</div><section className="mt-5 rounded-xl border border-[#e3d8d1] bg-white p-6">{tab === "Overview" ? <dl className="grid gap-x-8 gap-y-5 sm:grid-cols-2"><Info label="Customer" value={project.customerName} /><Info label="Status" value={statusLabel(project.status)} /><Info label="Project type" value={project.projectType} /><Info label="Estimated value" value={money(project.estimatedValue)} /><Info label="Location" value={project.location} /><Info label="Assigned sales agent" value={project.assignedSalesAgent} /><Info label="Start date" value={project.startDate} /><Info label="Required delivery" value={project.requiredDeliveryDate} /><Info label="Description" value={project.description} wide /><Info label="Internal notes" value={project.notes} wide /></dl> : <p className="py-10 text-center text-sm text-[#786961]">No {tab.toLowerCase()} are linked to this project yet.</p>}</section></section>;
}
function Info({ label, value, wide = false }: { label: string; value?: string; wide?: boolean }) { return <div className={wide ? "sm:col-span-2" : ""}><dt className="text-xs font-semibold uppercase tracking-wider text-[#786961]">{label}</dt><dd className="mt-1 whitespace-pre-wrap text-sm">{value || "Not set"}</dd></div>; }
