import { useEffect, useState, type FormEvent } from "react";
import { ArrowLeft, BriefcaseBusiness, ChevronRight, Grid2X2, LayoutList, Mail, MapPin, Pencil, Phone, Plus, Trash2, UsersRound } from "lucide-react";
import { useRouter } from "../../../app/providers/router";
import { api } from "../../../shared/api/client";
import { Button, DataTable, PaginationControls } from "../../../shared/ui";

type Contact = { id?: string; name: string; role?: string; email?: string; phone?: string };
type Address = { id?: string; label: string; line1: string; line2?: string; city?: string; country?: string; postalCode?: string };
type Customer = { id: string; type: "INDIVIDUAL" | "COMPANY"; name: string; companyName?: string; email?: string; phone?: string; notes?: string; active: boolean; contacts: Contact[]; addresses: Address[] };
type Page = { content: Customer[]; page: number; totalPages: number; totalElements: number };
const field = "h-10 w-full rounded-md border border-[#d8ccc4] px-3 text-sm outline-none focus:border-[#110703]";

export function CustomersPage() {
  const [items, setItems] = useState<Customer[]>([]); const [screen, setScreen] = useState<"list" | "form" | "edit" | "detail">("list"); const [detail, setDetail] = useState<Customer | null>(null); const [view, setView] = useState<"cards" | "list">("cards"); const [page, setPage] = useState(0); const [pageData, setPageData] = useState<Page>({ content: [], page: 0, totalPages: 0, totalElements: 0 }); const [loading, setLoading] = useState(false);
  async function load(nextPage = page) { setLoading(true); try { const result = await api<Page>(`/customers?page=${nextPage}&size=20`); setItems(result.content); setPageData(result); setPage(result.page); } finally { setLoading(false); } }
  useEffect(() => { void load(); }, []);
  if (screen === "form" || (screen === "edit" && detail)) return <CustomerForm initial={screen === "edit" ? detail! : undefined} back={() => setScreen(screen === "edit" ? "detail" : "list")} saved={() => { setScreen("list"); void load(0); }} />;
  if (screen === "detail" && detail) return <CustomerDetail customer={detail} edit={() => setScreen("edit")} back={() => { setScreen("list"); void load(); }} remove={async () => { if (!window.confirm(`Delete ${detail.name}? This cannot be undone.`)) return; try { await api(`/customers/${detail.id}`, { method: "DELETE" }); setDetail(null); setScreen("list"); await load(0); } catch (reason) { window.alert(reason instanceof Error ? reason.message : "The customer could not be deleted."); } }} />;
  const open = async (customer: Customer) => { setDetail(await api<Customer>(`/customers/${customer.id}`)); setScreen("detail"); };
  return <section className="mx-auto max-w-6xl px-4 py-7 sm:px-7">
    <header className="flex flex-wrap items-end justify-between gap-4 border-b border-[#dfd4cd] pb-6"><div><p className="text-[10px] font-bold tracking-[.18em] text-[#765847]">CUSTOMER DIRECTORY</p><h1 className="mt-2 font-sans text-4xl">Customers</h1><p className="mt-2 text-sm text-[#786961]">Open customer profiles from a visual directory; use the list for a compact contact register.</p></div><div className="flex items-center gap-2"><div className="inline-flex rounded-md border border-[#d8ccc4] bg-white p-1"><button type="button" onClick={() => setView("cards")} className={`inline-flex h-8 items-center gap-1.5 rounded px-2.5 text-xs font-semibold ${view === "cards" ? "bg-[#21140f] text-white" : "text-[#786961]"}`}><Grid2X2 size={14} /> Profiles</button><button type="button" onClick={() => setView("list")} className={`inline-flex h-8 items-center gap-1.5 rounded px-2.5 text-xs font-semibold ${view === "list" ? "bg-[#21140f] text-white" : "text-[#786961]"}`}><LayoutList size={14} /> List</button></div><Button onClick={() => setScreen("form")}><Plus size={16} /> Add customer</Button></div></header>
    {items.length === 0 ? <CustomerEmptyState /> : view === "cards" ? <CustomerCards items={items} open={customer => void open(customer)} /> : <div className="mt-6 overflow-hidden rounded-xl border border-[#e3d8d1] bg-white"><DataTable><thead className="bg-[#faf7f5] text-xs"><tr><th className="px-5 py-3">Name</th><th className="px-5 py-3">Type</th><th className="px-5 py-3">Company</th><th className="px-5 py-3">Phone</th><th className="px-5 py-3">Email</th></tr></thead><tbody>{items.map(customer => <tr key={customer.id} onClick={() => void open(customer)} className="cursor-pointer border-t border-[#f0e8e4] hover:bg-[#fdfaf8]"><td className="px-5 py-4 font-semibold">{customer.name}</td><td className="px-5 py-4 text-sm">{customer.type === "COMPANY" ? "Company" : "Individual"}</td><td className="px-5 py-4 text-sm">{customer.companyName ?? "—"}</td><td className="px-5 py-4 text-sm">{customer.phone ?? "—"}</td><td className="px-5 py-4 text-sm">{customer.email ?? "—"}</td></tr>)}</tbody></DataTable></div>}<PaginationControls page={page} totalPages={pageData.totalPages} totalElements={pageData.totalElements} itemCount={items.length} loading={loading} onPageChange={nextPage => void load(nextPage)} noun="customers" />
  </section>;
}

function CustomerCards({ items, open }: { items: Customer[]; open: (customer: Customer) => void }) { return <div className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{items.map(customer => <button key={customer.id} type="button" onClick={() => open(customer)} className="group rounded-xl border border-[#e3d8d1] bg-white p-5 text-left transition hover:-translate-y-0.5 hover:border-[#aa7756] hover:shadow-lg hover:shadow-[#4b2d1a]/10"><div className="flex items-start justify-between gap-3"><div className="grid size-10 place-items-center rounded-full bg-[#f4ece8] text-sm font-bold text-[#765847]">{customer.name.slice(0, 1).toUpperCase()}</div><span className={`rounded-full px-2 py-1 text-[10px] font-bold uppercase tracking-wide ${customer.active ? "bg-emerald-50 text-emerald-800" : "bg-[#f3efeb] text-[#66554b]"}`}>{customer.active ? "Active" : "Inactive"}</span></div><p className="mt-4 font-sans text-xl">{customer.name}</p><p className="mt-1 min-h-5 text-sm text-[#786961]">{customer.companyName ?? (customer.type === "COMPANY" ? "Company record" : "Individual customer")}</p><div className="mt-5 grid grid-cols-2 gap-2 border-t border-[#eee6e1] pt-3 text-xs"><p className="text-[#786961]"><b className="block text-[#21140f]">{customer.contacts.length}</b>contacts</p><p className="text-[#786961]"><b className="block text-[#21140f]">{customer.addresses.length}</b>addresses</p></div><p className="mt-3 truncate text-xs text-[#786961]">{customer.email ?? customer.phone ?? "No contact details yet"}</p></button>)}</div>; }

function CustomerEmptyState() {
  return <section className="mt-6 overflow-hidden rounded-xl border border-[#e3d8d1] bg-white"><div className="grid min-h-64 place-items-center px-6 py-10 text-center"><div><div className="mx-auto grid size-12 place-items-center rounded-full bg-[#f4ece8] text-[#765847]"><UsersRound size={22} /></div><p className="mt-4 text-sm font-medium text-[#786961]">No customers yet.</p></div></div></section>;
}

function CustomerForm({ initial, back, saved }: { initial?: Customer; back: () => void; saved: () => void }) {
  const [form, setForm] = useState({ type: initial?.type ?? "INDIVIDUAL", name: initial?.name ?? "", companyName: initial?.companyName ?? "", email: initial?.email ?? "", phone: initial?.phone ?? "", notes: initial?.notes ?? "" });
  const update = (key: string, value: string) => setForm(current => ({ ...current, [key]: value }));
  async function submit(event: FormEvent) { event.preventDefault(); await api(initial ? `/customers/${initial.id}` : "/customers", { method: initial ? "PUT" : "POST", body: JSON.stringify({ ...form, companyName: form.companyName || null, email: form.email || null, phone: form.phone || null, notes: form.notes || null, contacts: [], addresses: [] }) }); saved(); }
  return <section className="mx-auto max-w-3xl px-4 py-7"><button onClick={back} className="inline-flex gap-2 text-sm"><ArrowLeft size={16} /> Customers</button><form onSubmit={submit} className="mt-5 rounded-xl border border-[#e3d8d1] bg-white p-6"><h1 className="font-sans text-3xl">{initial ? "Edit customer" : "New customer"}</h1><div className="mt-5 grid gap-4 md:grid-cols-2"><label>Type<select value={form.type} onChange={event => update("type", event.target.value)} className={field}><option value="INDIVIDUAL">Individual</option><option value="COMPANY">Company</option></select></label><label>Name *<input required value={form.name} onChange={event => update("name", event.target.value)} className={field} /></label>{form.type === "COMPANY" && <label>Company name<input value={form.companyName} onChange={event => update("companyName", event.target.value)} className={field} /></label>}<label>Email<input type="email" value={form.email} onChange={event => update("email", event.target.value)} className={field} /></label><label>Phone<input value={form.phone} onChange={event => update("phone", event.target.value)} className={field} /></label></div><label className="mt-4 grid gap-1">Notes<textarea value={form.notes} onChange={event => update("notes", event.target.value)} className="min-h-24 border p-3" /></label><div className="mt-5 flex justify-end gap-2"><Button type="button" variant="outline" onClick={back}>Cancel</Button><Button type="submit">{initial ? "Save changes" : "Save customer"}</Button></div></form></section>;
}

function CustomerDetail({ customer, back, edit, remove }: { customer: Customer; back: () => void; edit: () => void; remove: () => void }) {
  return <section className="mx-auto max-w-6xl px-4 py-7 sm:px-7"><button onClick={back} className="inline-flex items-center gap-2 text-sm font-semibold text-[#6e5b51] transition hover:text-[#110703]"><ArrowLeft size={16} /> Customers</button><header className="mt-6 overflow-hidden rounded-2xl border border-[#dfd4cd] bg-[#21140f] text-white shadow-[0_18px_50px_rgba(57,35,23,0.12)]"><div className="flex flex-wrap items-end justify-between gap-6 px-6 py-7 sm:px-8 sm:py-8"><div className="flex items-center gap-5"><div className="grid size-16 shrink-0 place-items-center rounded-2xl bg-[#c89167] font-sans text-3xl text-[#21140f]">{customer.name.slice(0, 1).toUpperCase()}</div><div><p className="text-[11px] font-bold tracking-[.18em] text-[#e4c5ae]">CUSTOMER PROFILE</p><h1 className="mt-2 font-sans text-3xl tracking-tight sm:text-4xl">{customer.name}</h1><p className="mt-2 text-sm text-[#d7c0b1]">{customer.companyName ?? (customer.type === "COMPANY" ? "Company account" : "Individual customer")}</p></div></div><div className="flex items-center gap-2"><button type="button" onClick={edit} className="inline-flex items-center gap-2 rounded-lg bg-white/10 px-3 py-2 text-xs font-semibold hover:bg-white/20"><Pencil size={14} />Edit</button><button type="button" onClick={remove} className="inline-flex items-center gap-2 rounded-lg bg-red-500/20 px-3 py-2 text-xs font-semibold text-red-100 hover:bg-red-500/30"><Trash2 size={14} />Delete</button><span className={`rounded-full px-3 py-1.5 text-xs font-bold uppercase tracking-wide ${customer.active ? "bg-[#d5eadc] text-[#245c3a]" : "bg-white/10 text-[#eaded7]"}`}>{customer.active ? "Active account" : "Inactive account"}</span></div></div><div className="grid border-t border-white/10 sm:grid-cols-3"><HeroStat label="Contacts" value={String(customer.contacts.length)} /><HeroStat label="Addresses" value={String(customer.addresses.length)} /><HeroStat label="Customer type" value={customer.type === "COMPANY" ? "Company" : "Individual"} /></div></header><Overview customer={customer} /><div className="mt-8 grid gap-5 lg:grid-cols-2"><ProfileSection title="Contacts" count={customer.contacts.length}><ContactRows contacts={customer.contacts} /></ProfileSection><ProfileSection title="Addresses" count={customer.addresses.length}><AddressRows addresses={customer.addresses} /></ProfileSection><div className="lg:col-span-2"><ProfileSection title="Projects"><CustomerProjects customerId={customer.id} /></ProfileSection></div><ProfileSection title="RFQs"><EmptyRecords label="No RFQs linked to this customer yet." /></ProfileSection><ProfileSection title="Quotations"><EmptyRecords label="No quotations linked to this customer yet." /></ProfileSection><ProfileSection title="Orders"><EmptyRecords label="No orders linked to this customer yet." /></ProfileSection></div></section>;
}

function ProfileSection({ title, count, children }: { title: string; count?: number; children: React.ReactNode }) { return <section className="rounded-2xl border border-[#e3d8d1] bg-white p-5 shadow-[0_8px_30px_rgba(76,49,35,0.04)] sm:p-7"><div className="flex items-center justify-between gap-3 border-b border-[#eee6e1] pb-4"><h2 className="font-sans text-2xl">{title}</h2>{count !== undefined && <span className="rounded-full bg-[#f4ece8] px-2.5 py-1 text-xs font-bold text-[#765847]">{count}</span>}</div><div className="pt-5">{children}</div></section>; }
function ContactRows({ contacts }: { contacts: Contact[] }) { return contacts.length ? <div className="grid gap-3 md:grid-cols-2">{contacts.map((contact, index) => <article key={contact.id ?? `${contact.name}-${index}`} className="rounded-xl border border-[#e3d8d1] bg-[#fdfbf9] p-4"><p className="font-semibold text-[#33251f]">{contact.name}</p><p className="mt-1 text-sm text-[#786961]">{contact.role ?? "Contact"}</p><div className="mt-4 space-y-1 text-xs text-[#5f483c]">{contact.email && <p>{contact.email}</p>}{contact.phone && <p>{contact.phone}</p>}{!contact.email && !contact.phone && <p>No contact details recorded.</p>}</div></article>)}</div> : <EmptyRecords label="No contacts yet." />; }
function AddressRows({ addresses }: { addresses: Address[] }) { return addresses.length ? <div className="grid gap-3 md:grid-cols-2">{addresses.map((address, index) => <article key={address.id ?? `${address.label}-${index}`} className="rounded-xl border border-[#e3d8d1] bg-[#fdfbf9] p-4"><div className="flex items-start gap-3"><MapPin size={17} className="mt-0.5 shrink-0 text-[#8d5f41]" /><div><p className="font-semibold text-[#33251f]">{address.label}</p><p className="mt-2 text-sm leading-6 text-[#5f483c]">{address.line1}{address.line2 ? <><br />{address.line2}</> : null}{address.city ? <><br />{address.city}</> : null}{address.country ? <>, {address.country}</> : null}</p></div></div></article>)}</div> : <EmptyRecords label="No addresses yet." />; }
function EmptyRecords({ label }: { label: string }) { return <p className="rounded-xl border border-dashed border-[#d8ccc4] bg-[#fdfbf9] px-4 py-8 text-center text-sm text-[#786961]">{label}</p>; }

function HeroStat({ label, value }: { label: string; value: string }) { return <div className="border-r border-white/10 px-6 py-4 last:border-r-0 sm:px-8"><p className="text-[10px] font-bold uppercase tracking-[.16em] text-[#bda697]">{label}</p><p className="mt-1 font-sans text-xl text-white">{value}</p></div>; }
function Overview({ customer }: { customer: Customer }) { return <div className="mt-6 grid gap-5 lg:grid-cols-[1.1fr_.9fr]"><section className="rounded-2xl border border-[#e3d8d1] bg-white p-5 shadow-[0_8px_30px_rgba(76,49,35,0.04)] sm:p-7"><p className="text-[11px] font-bold tracking-[.16em] text-[#806f65]">DIRECT CONTACT</p><h2 className="mt-2 font-sans text-2xl">How to reach them</h2><div className="mt-6 grid gap-3 sm:grid-cols-2"><ContactTile icon={<Mail size={17} />} label="Email" value={customer.email ?? "Not set"} /><ContactTile icon={<Phone size={17} />} label="Phone" value={customer.phone ?? "Not set"} /></div><div className="mt-6 border-t border-[#eee6e1] pt-5"><p className="text-[11px] font-bold tracking-[.16em] text-[#806f65]">ACCOUNT NOTES</p><p className="mt-2 text-sm leading-6 text-[#5f483c]">{customer.notes ?? "No notes have been added to this customer yet."}</p></div></section><section className="rounded-2xl border border-[#e3d8d1] bg-[#f7f1ed] p-5 sm:p-7"><p className="text-[11px] font-bold tracking-[.16em] text-[#806f65]">RELATIONSHIP SNAPSHOT</p><h2 className="mt-2 font-sans text-2xl">Customer workspace</h2><div className="mt-6 space-y-4"><Snapshot icon={<BriefcaseBusiness size={17} />} label="Projects" value="Project history is available in the Projects tab." /><Snapshot icon={<MapPin size={17} />} label="Addresses" value={customer.addresses.length ? `${customer.addresses.length} saved address${customer.addresses.length === 1 ? "" : "es"}` : "No saved addresses"} /></div></section></div>; }
function ContactTile({ icon, label, value }: { icon: React.ReactNode; label: string; value: string }) { return <div className="rounded-xl border border-[#e3d8d1] bg-[#fdfbf9] p-4"><div className="flex items-center gap-2 text-[#8d5f41]">{icon}<p className="text-[10px] font-bold uppercase tracking-[.14em] text-[#806f65]">{label}</p></div><p className="mt-3 break-words text-sm font-semibold text-[#33251f]">{value}</p></div>; }
function Snapshot({ icon, label, value }: { icon: React.ReactNode; label: string; value: string }) { return <div className="flex items-start gap-3 border-b border-[#e6d9d1] pb-4 last:border-0 last:pb-0"><div className="mt-0.5 text-[#8d5f41]">{icon}</div><div><p className="text-sm font-semibold text-[#33251f]">{label}</p><p className="mt-1 text-xs leading-5 text-[#786961]">{value}</p></div></div>; }

function CustomerProjects({ customerId }: { customerId: string }) { const { navigate } = useRouter(); const [projects, setProjects] = useState<{ id: string; name: string; status: string; projectType?: string; location?: string }[]>([]); const [page, setPage] = useState(0); const [data, setData] = useState<{ page: number; totalPages: number; totalElements: number }>({ page: 0, totalPages: 0, totalElements: 0 }); async function load(nextPage = page) { const result = await api<{ content: { id: string; name: string; status: string; projectType?: string; location?: string }[]; page: number; totalPages: number; totalElements: number }>(`/projects?customerId=${customerId}&page=${nextPage}&size=8`); setProjects(result.content); setData(result); setPage(result.page); } useEffect(() => { void load(0); }, [customerId]); return <>{projects.length ? <div className="grid gap-2 sm:grid-cols-2">{projects.map(project => <button type="button" key={project.id} onClick={() => navigate(`/projects/${project.id}`)} className="group flex w-full items-center justify-between gap-4 rounded-xl border border-[#e3d8d1] bg-[#fdfbf9] px-4 py-3 text-left transition hover:border-[#aa7756] hover:bg-[#fffaf6] hover:shadow-sm"><span className="min-w-0"><span className="block truncate font-semibold text-[#33251f]">{project.name}</span><span className="mt-1 block truncate text-sm text-[#786961]">{project.projectType ?? "Project"}{project.location ? ` · ${project.location}` : ""}</span></span><span className="flex shrink-0 items-center gap-2"><span className="rounded-full bg-[#f4ece8] px-2 py-1 text-[10px] font-bold uppercase tracking-wide text-[#765847]">{project.status.replaceAll("_", " ")}</span><ChevronRight size={16} className="text-[#aa7756] transition-transform group-hover:translate-x-0.5" /></span></button>)}</div> : <p className="py-8 text-center text-sm text-[#786961]">No projects yet.</p>}<PaginationControls page={page} totalPages={data.totalPages} totalElements={data.totalElements} itemCount={projects.length} onPageChange={nextPage => void load(nextPage)} noun="projects" /></>; }
function List({ rows, empty }: { rows: string[]; empty: string }) { return rows.length ? <div className="grid gap-3">{rows.map(item => <p key={item} className="border-b pb-3">{item}</p>)}</div> : <p className="py-8 text-center text-sm text-[#786961]">{empty}</p>; }
