import { useEffect, useState, type FormEvent } from "react";
import { ArrowLeft, Grid2X2, LayoutList, Plus, UsersRound } from "lucide-react";
import { api } from "../../../shared/api/client";
import { Button, DataTable } from "../../../shared/ui";

type Contact = { id?: string; name: string; role?: string; email?: string; phone?: string };
type Address = { id?: string; label: string; line1: string; line2?: string; city?: string; country?: string; postalCode?: string };
type Customer = { id: string; type: "INDIVIDUAL" | "COMPANY"; name: string; companyName?: string; email?: string; phone?: string; notes?: string; active: boolean; contacts: Contact[]; addresses: Address[] };
type Page = { content: Customer[] };
const field = "h-10 w-full rounded-md border border-[#d8ccc4] px-3 text-sm outline-none focus:border-[#110703]";

export function CustomersPage() {
  const [items, setItems] = useState<Customer[]>([]); const [screen, setScreen] = useState<"list" | "form" | "detail">("list"); const [detail, setDetail] = useState<Customer | null>(null); const [view, setView] = useState<"cards" | "list">("cards");
  async function load() { setItems((await api<Page>("/customers?size=100")).content); }
  useEffect(() => { void load(); }, []);
  if (screen === "form") return <CustomerForm back={() => setScreen("list")} saved={() => { setScreen("list"); void load(); }} />;
  if (screen === "detail" && detail) return <CustomerDetail customer={detail} back={() => { setScreen("list"); void load(); }} />;
  const open = async (customer: Customer) => { setDetail(await api<Customer>(`/customers/${customer.id}`)); setScreen("detail"); };
  return <section className="mx-auto max-w-6xl px-4 py-7 sm:px-7">
    <header className="flex flex-wrap items-end justify-between gap-4 border-b border-[#dfd4cd] pb-6"><div><p className="text-[10px] font-bold tracking-[.18em] text-[#765847]">CUSTOMER DIRECTORY</p><h1 className="mt-2 font-sans text-4xl">Customers</h1><p className="mt-2 text-sm text-[#786961]">Open customer profiles from a visual directory; use the list for a compact contact register.</p></div><div className="flex items-center gap-2"><div className="inline-flex rounded-md border border-[#d8ccc4] bg-white p-1"><button type="button" onClick={() => setView("cards")} className={`inline-flex h-8 items-center gap-1.5 rounded px-2.5 text-xs font-semibold ${view === "cards" ? "bg-[#21140f] text-white" : "text-[#786961]"}`}><Grid2X2 size={14} /> Profiles</button><button type="button" onClick={() => setView("list")} className={`inline-flex h-8 items-center gap-1.5 rounded px-2.5 text-xs font-semibold ${view === "list" ? "bg-[#21140f] text-white" : "text-[#786961]"}`}><LayoutList size={14} /> List</button></div><Button onClick={() => setScreen("form")}><Plus size={16} /> Add customer</Button></div></header>
    {items.length === 0 ? <CustomerEmptyState /> : view === "cards" ? <CustomerCards items={items} open={customer => void open(customer)} /> : <div className="mt-6 overflow-hidden rounded-xl border border-[#e3d8d1] bg-white"><DataTable><thead className="bg-[#faf7f5] text-xs"><tr><th className="px-5 py-3">Name</th><th className="px-5 py-3">Type</th><th className="px-5 py-3">Company</th><th className="px-5 py-3">Phone</th><th className="px-5 py-3">Email</th></tr></thead><tbody>{items.map(customer => <tr key={customer.id} onClick={() => void open(customer)} className="cursor-pointer border-t border-[#f0e8e4] hover:bg-[#fdfaf8]"><td className="px-5 py-4 font-semibold">{customer.name}</td><td className="px-5 py-4 text-sm">{customer.type === "COMPANY" ? "Company" : "Individual"}</td><td className="px-5 py-4 text-sm">{customer.companyName ?? "—"}</td><td className="px-5 py-4 text-sm">{customer.phone ?? "—"}</td><td className="px-5 py-4 text-sm">{customer.email ?? "—"}</td></tr>)}</tbody></DataTable></div>}
  </section>;
}

function CustomerCards({ items, open }: { items: Customer[]; open: (customer: Customer) => void }) { return <div className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{items.map(customer => <button key={customer.id} type="button" onClick={() => open(customer)} className="group rounded-xl border border-[#e3d8d1] bg-white p-5 text-left transition hover:-translate-y-0.5 hover:border-[#aa7756] hover:shadow-lg hover:shadow-[#4b2d1a]/10"><div className="flex items-start justify-between gap-3"><div className="grid size-10 place-items-center rounded-full bg-[#f4ece8] text-sm font-bold text-[#765847]">{customer.name.slice(0, 1).toUpperCase()}</div><span className={`rounded-full px-2 py-1 text-[10px] font-bold uppercase tracking-wide ${customer.active ? "bg-emerald-50 text-emerald-800" : "bg-[#f3efeb] text-[#66554b]"}`}>{customer.active ? "Active" : "Inactive"}</span></div><p className="mt-4 font-sans text-xl">{customer.name}</p><p className="mt-1 min-h-5 text-sm text-[#786961]">{customer.companyName ?? (customer.type === "COMPANY" ? "Company record" : "Individual customer")}</p><div className="mt-5 grid grid-cols-2 gap-2 border-t border-[#eee6e1] pt-3 text-xs"><p className="text-[#786961]"><b className="block text-[#21140f]">{customer.contacts.length}</b>contacts</p><p className="text-[#786961]"><b className="block text-[#21140f]">{customer.addresses.length}</b>addresses</p></div><p className="mt-3 truncate text-xs text-[#786961]">{customer.email ?? customer.phone ?? "No contact details yet"}</p></button>)}</div>; }

function CustomerEmptyState() {
  return <section className="mt-6 overflow-hidden rounded-xl border border-[#e3d8d1] bg-white"><div className="grid min-h-64 place-items-center px-6 py-10 text-center"><div><div className="mx-auto grid size-12 place-items-center rounded-full bg-[#f4ece8] text-[#765847]"><UsersRound size={22} /></div><p className="mt-4 text-sm font-medium text-[#786961]">No customers yet.</p></div></div></section>;
}

function CustomerForm({ back, saved }: { back: () => void; saved: () => void }) {
  const [form, setForm] = useState({ type: "INDIVIDUAL", name: "", companyName: "", email: "", phone: "", notes: "" });
  const update = (key: string, value: string) => setForm(current => ({ ...current, [key]: value }));
  async function submit(event: FormEvent) { event.preventDefault(); await api("/customers", { method: "POST", body: JSON.stringify({ ...form, companyName: form.companyName || null, email: form.email || null, phone: form.phone || null, notes: form.notes || null, contacts: [], addresses: [] }) }); saved(); }
  return <section className="mx-auto max-w-3xl px-4 py-7"><button onClick={back} className="inline-flex gap-2 text-sm"><ArrowLeft size={16} /> Customers</button><form onSubmit={submit} className="mt-5 rounded-xl border border-[#e3d8d1] bg-white p-6"><h1 className="font-sans text-3xl">New customer</h1><div className="mt-5 grid gap-4 md:grid-cols-2"><label>Type<select value={form.type} onChange={event => update("type", event.target.value)} className={field}><option value="INDIVIDUAL">Individual</option><option value="COMPANY">Company</option></select></label><label>Name *<input required value={form.name} onChange={event => update("name", event.target.value)} className={field} /></label>{form.type === "COMPANY" && <label>Company name<input value={form.companyName} onChange={event => update("companyName", event.target.value)} className={field} /></label>}<label>Email<input type="email" value={form.email} onChange={event => update("email", event.target.value)} className={field} /></label><label>Phone<input value={form.phone} onChange={event => update("phone", event.target.value)} className={field} /></label></div><label className="mt-4 grid gap-1">Notes<textarea value={form.notes} onChange={event => update("notes", event.target.value)} className="min-h-24 border p-3" /></label><div className="mt-5 flex justify-end gap-2"><Button type="button" variant="outline" onClick={back}>Cancel</Button><Button type="submit">Save customer</Button></div></form></section>;
}

function CustomerDetail({ customer, back }: { customer: Customer; back: () => void }) {
  const [tab, setTab] = useState("Overview"); const tabs = ["Overview", "Contacts", "Addresses", "Projects", "RFQs", "Quotations", "Orders"];
  return <section className="mx-auto max-w-5xl px-4 py-7"><button onClick={back} className="inline-flex gap-2 text-sm"><ArrowLeft size={16} /> Customers</button><h1 className="mt-5 font-sans text-4xl">{customer.name}</h1><p className="mt-2 text-sm text-[#786961]">{customer.companyName ?? customer.type}</p><div className="mt-6 flex flex-wrap gap-2 border-b">{tabs.map(item => <button key={item} onClick={() => setTab(item)} className={`px-3 py-2 text-sm ${tab === item ? "border-b-2 border-[#110703] font-semibold" : "text-[#786961]"}`}>{item}</button>)}</div><section className="mt-5 rounded-xl border border-[#e3d8d1] bg-white p-6">{tab === "Overview" ? <dl className="grid gap-4 sm:grid-cols-2"><div><dt>Email</dt><dd>{customer.email ?? "Not set"}</dd></div><div><dt>Phone</dt><dd>{customer.phone ?? "Not set"}</dd></div><div className="sm:col-span-2"><dt>Notes</dt><dd>{customer.notes ?? "No notes yet"}</dd></div></dl> : tab === "Contacts" ? <List rows={customer.contacts.map(item => item.name + (item.role ? ` · ${item.role}` : ""))} empty="No contacts yet." /> : tab === "Addresses" ? <List rows={customer.addresses.map(item => `${item.label} · ${item.line1}`)} empty="No addresses yet." /> : tab === "Projects" ? <CustomerProjects customerId={customer.id} /> : <List rows={[]} empty="No records yet." />}</section></section>;
}

function CustomerProjects({ customerId }: { customerId: string }) { const [projects, setProjects] = useState<{ id: string; name: string; status: string; projectType?: string; location?: string }[]>([]); useEffect(() => { void api<{ content: { id: string; name: string; status: string; projectType?: string; location?: string }[] }>(`/projects?customerId=${customerId}&size=100`).then(page => setProjects(page.content)); }, [customerId]); return projects.length ? <div className="grid gap-3">{projects.map(project => <div key={project.id} className="border-b pb-3"><p className="font-semibold">{project.name}</p><p className="mt-1 text-sm text-[#786961]">{project.projectType ?? "Project"}{project.location ? ` · ${project.location}` : ""} · {project.status.replaceAll("_", " ")}</p></div>)}</div> : <p className="py-8 text-center text-sm text-[#786961]">No projects yet.</p>; }
function List({ rows, empty }: { rows: string[]; empty: string }) { return rows.length ? <div className="grid gap-3">{rows.map(item => <p key={item} className="border-b pb-3">{item}</p>)}</div> : <p className="py-8 text-center text-sm text-[#786961]">{empty}</p>; }
