import { useEffect, useState, type FormEvent } from "react";
import { ArrowLeft, CheckCircle2, ClipboardCheck, PackageCheck, Plus, Truck, XCircle } from "lucide-react";
import { api, RequestError } from "../../../shared/api/client";
import { Button, DataTable, TextField } from "../../../shared/ui";

type DeliveryItem = { id: string; orderItemId: string; materialName: string; variantLabel: string; quantityM2: number };
type Delivery = { id: string; number: string; orderId: string; orderNumber: string; customerName: string; projectName: string; scheduledDate?: string; status: string; notes?: string; dispatchedAt?: string; deliveredAt?: string; items: DeliveryItem[] };
type OrderItem = { id: string; materialName: string; variantLabel: string; quantityM2: number };
type Order = { id: string; number: string; customerName: string; projectName: string; status: string; items: OrderItem[] };

const field = "mt-1 h-10 w-full rounded-md border border-[#d8ccc4] bg-white px-3 text-sm outline-none focus:border-[#110703]";
const display = (value: string) => value.replaceAll("_", " ").toLowerCase().replace(/\b\w/g, letter => letter.toUpperCase());

export function DeliveriesPage() {
  const [list, setList] = useState<Delivery[]>([]); const [detail, setDetail] = useState<Delivery | null>(null); const [planning, setPlanning] = useState(false); const [error, setError] = useState("");
  async function load() { try { setList((await api<{ content: Delivery[] }>("/deliveries?size=100")).content); } catch (cause) { setError((cause as Error).message); } }
  useEffect(() => { void load(); }, []);
  if (planning) return <PlanDelivery back={() => setPlanning(false)} done={async delivery => { await load(); setDetail(delivery); setPlanning(false); }} />;
  if (detail) return <DeliveryDetail delivery={detail} back={() => setDetail(null)} refresh={async () => { const next = await api<Delivery>(`/deliveries/${detail.id}`); setDetail(next); await load(); }} />;
  return <section className="mx-auto max-w-6xl px-4 py-7"><header className="flex flex-wrap items-end justify-between gap-4 border-b pb-6"><div><p className="text-xs tracking-widest">FULFILLMENT DESK</p><h1 className="font-serif text-4xl">Deliveries</h1><p className="mt-2 text-sm text-[#786961]">Plan physical dispatches against confirmed customer orders.</p></div><Button onClick={() => setPlanning(true)}><Plus size={16} /> Plan delivery</Button></header>{error && <p className="mt-4 text-sm text-red-700">{error}</p>}<div className="mt-5 overflow-hidden rounded-xl border bg-white"><DataTable><thead><tr><th>Delivery</th><th>Order</th><th>Customer / project</th><th>Scheduled</th><th>Status</th></tr></thead><tbody>{!list.length ? <tr><td colSpan={5} className="py-12 text-center text-sm text-[#786961]">No deliveries planned. Confirm an order, then schedule its dispatch.</td></tr> : list.map(delivery => <tr key={delivery.id} className="cursor-pointer" onClick={() => void api<Delivery>(`/deliveries/${delivery.id}`).then(setDetail)}><td>{delivery.number}</td><td>{delivery.orderNumber}</td><td>{delivery.customerName}<br /><small>{delivery.projectName}</small></td><td>{delivery.scheduledDate ?? "Not scheduled"}</td><td>{display(delivery.status)}</td></tr>)}</tbody></DataTable></div></section>;
}

function PlanDelivery({ back, done }: { back: () => void; done: (delivery: Delivery) => Promise<void> }) {
  const [orders, setOrders] = useState<Order[]>([]); const [order, setOrder] = useState<Order | null>(null); const [orderId, setOrderId] = useState(""); const [quantities, setQuantities] = useState<Record<string, string>>({}); const [scheduledDate, setScheduledDate] = useState(""); const [notes, setNotes] = useState(""); const [error, setError] = useState(""); const [saving, setSaving] = useState(false);
  useEffect(() => { void api<{ content: Order[] }>("/orders?size=100").then(page => setOrders(page.content.filter(item => ["CONFIRMED", "PREPARING", "PARTIALLY_DELIVERED"].includes(item.status)))).catch(cause => setError((cause as Error).message)); }, []);
  async function selectOrder(id: string) { setOrderId(id); setQuantities({}); if (!id) { setOrder(null); return; } try { setOrder(await api<Order>(`/orders/${id}`)); } catch (cause) { setError((cause as Error).message); } }
  async function submit(event: FormEvent) { event.preventDefault(); if (!order) return; setSaving(true); setError(""); try { const items = order.items.map(item => ({ orderItemId: item.id, quantityM2: Number(quantities[item.id] || 0) })).filter(item => item.quantityM2 > 0); const delivery = await api<Delivery>("/deliveries", { method: "POST", body: JSON.stringify({ orderId: order.id, scheduledDate: scheduledDate || null, notes: notes || null, items }) }); await done(delivery); } catch (cause) { setError((cause as RequestError).message); } finally { setSaving(false); } }
  return <section className="mx-auto max-w-4xl px-4 py-7"><button onClick={back} className="inline-flex items-center gap-2 text-sm"><ArrowLeft size={16} /> Deliveries</button><header className="mt-5 border-b pb-6"><p className="text-xs tracking-widest">FULFILLMENT PLAN</p><h1 className="font-serif text-4xl">Plan delivery</h1><p className="mt-2 text-sm text-[#786961]">Choose the reserved order quantities that will leave the warehouse in this dispatch.</p></header><form onSubmit={submit} className="mt-6 rounded-xl border bg-white p-6"><label className="text-sm font-semibold">Confirmed order<select value={orderId} onChange={event => void selectOrder(event.target.value)} className={field} required><option value="">Select order</option>{orders.map(item => <option key={item.id} value={item.id}>{item.number} · {item.customerName}</option>)}</select></label>{order && <><div className="mt-6 border-t pt-5"><p className="text-sm font-semibold">Dispatch quantities</p>{order.items.map(item => <label key={item.id} className="mt-4 grid gap-1 text-sm sm:grid-cols-[1fr_180px] sm:items-end"><span><b>{item.materialName}</b><small className="block text-[#786961]">{item.variantLabel} · Ordered {item.quantityM2} m²</small></span><input className={field} type="number" min="0" step="0.001" placeholder="m² to dispatch" value={quantities[item.id] ?? ""} onChange={event => setQuantities(current => ({ ...current, [item.id]: event.target.value }))} /></label>)}</div><div className="mt-6 grid gap-4 sm:grid-cols-2"><TextField label="Scheduled date" type="date" value={scheduledDate} onChange={event => setScheduledDate(event.target.value)} /><label className="text-sm font-semibold">Dispatch note<textarea value={notes} onChange={event => setNotes(event.target.value)} className="mt-1 min-h-24 w-full rounded-md border border-[#d8ccc4] p-3 text-sm outline-none focus:border-[#110703]" placeholder="Delivery instructions or site contact" /></label></div></>}{error && <p className="mt-4 text-sm text-red-700">{error}</p>}<footer className="mt-6 flex justify-end gap-2"><Button type="button" variant="outline" onClick={back}>Cancel</Button><Button type="submit" loading={saving} disabled={!order}><ClipboardCheck size={16} /> Create delivery plan</Button></footer></form></section>;
}

function DeliveryDetail({ delivery, back, refresh }: { delivery: Delivery; back: () => void; refresh: () => Promise<void> }) {
  const [error, setError] = useState(""); const [working, setWorking] = useState(false);
  async function action(path: string) { setWorking(true); setError(""); try { await api(`/deliveries/${delivery.id}/${path}`, { method: "POST" }); await refresh(); } catch (cause) { setError((cause as Error).message); } finally { setWorking(false); } }
  return <section className="mx-auto max-w-5xl px-4 py-7"><button onClick={back} className="inline-flex items-center gap-2 text-sm"><ArrowLeft size={16} /> Deliveries</button><header className="mt-5 flex flex-wrap items-end justify-between gap-4 border-b pb-6"><div><p className="text-xs tracking-widest">DELIVERY NOTE</p><h1 className="font-serif text-4xl">{delivery.number}</h1><p className="mt-2 text-sm text-[#786961]">Order {delivery.orderNumber} · {delivery.customerName} · {delivery.projectName}</p></div><p className="font-semibold">{display(delivery.status)}</p></header><div className="mt-6 grid gap-4 sm:grid-cols-3"><article className="rounded-xl border bg-white p-5"><p className="text-xs text-[#786961]">Scheduled</p><p className="mt-2 font-semibold">{delivery.scheduledDate ?? "Not scheduled"}</p></article><article className="rounded-xl border bg-white p-5"><p className="text-xs text-[#786961]">Dispatched</p><p className="mt-2 font-semibold">{delivery.dispatchedAt ? new Date(delivery.dispatchedAt).toLocaleString() : "Not dispatched"}</p></article><article className="rounded-xl border bg-white p-5"><p className="text-xs text-[#786961]">Delivered</p><p className="mt-2 font-semibold">{delivery.deliveredAt ? new Date(delivery.deliveredAt).toLocaleString() : "Awaiting confirmation"}</p></article></div><section className="mt-5 overflow-hidden rounded-xl border bg-white"><div className="border-b px-5 py-4"><h2 className="font-semibold">Dispatch items</h2><p className="mt-1 text-sm text-[#786961]">Stock is reduced only when this delivery is dispatched.</p></div><DataTable><thead><tr><th>Material</th><th>Variant</th><th>Quantity</th></tr></thead><tbody>{delivery.items.map(item => <tr key={item.id}><td>{item.materialName}</td><td>{item.variantLabel}</td><td>{item.quantityM2} m²</td></tr>)}</tbody></DataTable></section>{delivery.notes && <p className="mt-5 rounded-xl border bg-white p-5 text-sm">{delivery.notes}</p>}{error && <p className="mt-4 text-sm text-red-700">{error}</p>}<div className="mt-6 flex flex-wrap gap-2">{delivery.status === "PLANNED" && <Button loading={working} onClick={() => void action("prepare")}><PackageCheck size={16} /> Start preparation</Button>}{["PLANNED", "PREPARING"].includes(delivery.status) && <Button loading={working} onClick={() => void action("dispatch")}><Truck size={16} /> Dispatch stock</Button>}{delivery.status === "DISPATCHED" && <Button loading={working} onClick={() => void action("confirm-delivered")}><CheckCircle2 size={16} /> Confirm delivered</Button>}{["PLANNED", "PREPARING"].includes(delivery.status) && <><Button variant="outline" loading={working} onClick={() => void action("fail")}><XCircle size={16} /> Mark failed</Button><Button variant="outline" loading={working} onClick={() => void action("cancel")}><XCircle size={16} /> Cancel delivery</Button></>}</div></section>;
}
