-- Preserve landing IDs so existing product URLs and a future API-backed landing integration remain stable.

alter table catalogue_categories add column source_category_id integer;
alter table stone_materials add column source_product_id bigint;

update catalogue_categories set source_category_id = 45, updated_at = current_timestamp where slug = 'marbre-local';
update catalogue_categories set source_category_id = 70, updated_at = current_timestamp where slug = 'pierre-naturelle-tahejart';
update catalogue_categories set source_category_id = 1, updated_at = current_timestamp where slug = 'granit';
update catalogue_categories set source_category_id = 18, updated_at = current_timestamp where slug = 'marbre';
update catalogue_categories set source_category_id = 85, updated_at = current_timestamp where slug = 'onyx';
update catalogue_categories set source_category_id = 86, updated_at = current_timestamp where slug = 'quartz';

update stone_materials set source_product_id = 209, updated_at = current_timestamp where slug = 'beige-taza';
update stone_materials set source_product_id = 210, updated_at = current_timestamp where slug = 'beige-taza-boucharde-210';
update stone_materials set source_product_id = 211, updated_at = current_timestamp where slug = 'beige-taza-vieille-211';
update stone_materials set source_product_id = 212, updated_at = current_timestamp where slug = 'beige-taza-brut-212';
update stone_materials set source_product_id = 213, updated_at = current_timestamp where slug = 'beige-taza-veinage-213';
update stone_materials set source_product_id = 214, updated_at = current_timestamp where slug = 'beige-taza-strie-214';
update stone_materials set source_product_id = 215, updated_at = current_timestamp where slug = 'gris-taza-polli-215';
update stone_materials set source_product_id = 216, updated_at = current_timestamp where slug = 'gris-taza-boucharde-216';
update stone_materials set source_product_id = 217, updated_at = current_timestamp where slug = 'gris-taza-vieille-217';
update stone_materials set source_product_id = 218, updated_at = current_timestamp where slug = 'gris-taza-brut-218';
update stone_materials set source_product_id = 219, updated_at = current_timestamp where slug = 'gris-taza-veinage-219';
update stone_materials set source_product_id = 220, updated_at = current_timestamp where slug = 'gris-taza-strie-220';
update stone_materials set source_product_id = 221, updated_at = current_timestamp where slug = 'gris-taza-sable-221';
update stone_materials set source_product_id = 222, updated_at = current_timestamp where slug = 'beige-taza-sable-222';
update stone_materials set source_product_id = 223, updated_at = current_timestamp where slug = 'zola-vieille-223';
update stone_materials set source_product_id = 224, updated_at = current_timestamp where slug = 'pierre-volcanique-224';
update stone_materials set source_product_id = 225, updated_at = current_timestamp where slug = 'volubilis-225';
update stone_materials set source_product_id = 226, updated_at = current_timestamp where slug = 'noir-khenifra-226';
update stone_materials set source_product_id = 228, updated_at = current_timestamp where slug = 'gris-tiflet-228';
update stone_materials set source_product_id = 229, updated_at = current_timestamp where slug = 'gris-benslimane-229';
update stone_materials set source_product_id = 230, updated_at = current_timestamp where slug = 'noir-azilal-230';
update stone_materials set source_product_id = 231, updated_at = current_timestamp where slug = 'jaune-bejaad-231';
update stone_materials set source_product_id = 232, updated_at = current_timestamp where slug = 'rouge-agadir-232';
update stone_materials set source_product_id = 233, updated_at = current_timestamp where slug = 'bir-jdid-233';
update stone_materials set source_product_id = 235, updated_at = current_timestamp where slug = 'eclate-beige-taza-235';
update stone_materials set source_product_id = 236, updated_at = current_timestamp where slug = 'eclate-gris-taza-236';
update stone_materials set source_product_id = 237, updated_at = current_timestamp where slug = 'eclate-noir-khenifra-237';
update stone_materials set source_product_id = 238, updated_at = current_timestamp where slug = 'eclate-noir-azilal-238';
update stone_materials set source_product_id = 239, updated_at = current_timestamp where slug = 'eclate-volubilis-239';
update stone_materials set source_product_id = 240, updated_at = current_timestamp where slug = 'eclate-rouge-rose-240';
update stone_materials set source_product_id = 241, updated_at = current_timestamp where slug = 'crazy-beige-taza-241';
update stone_materials set source_product_id = 242, updated_at = current_timestamp where slug = 'ardoise-verdatre-242';
update stone_materials set source_product_id = 243, updated_at = current_timestamp where slug = 'ardoise-violet-fonce-243';
update stone_materials set source_product_id = 244, updated_at = current_timestamp where slug = 'ardoise-244';
update stone_materials set source_product_id = 245, updated_at = current_timestamp where slug = 'ardoise-245';
update stone_materials set source_product_id = 246, updated_at = current_timestamp where slug = 'ardoise-246';
update stone_materials set source_product_id = 5000, updated_at = current_timestamp where slug = 'new-calacatta-gris';
update stone_materials set source_product_id = 5001, updated_at = current_timestamp where slug = 'new-calacata-dore-5001';
update stone_materials set source_product_id = 5002, updated_at = current_timestamp where slug = 'rose-porino-5002';
update stone_materials set source_product_id = 5003, updated_at = current_timestamp where slug = 'rose-avel-5003';
update stone_materials set source_product_id = 5004, updated_at = current_timestamp where slug = 'patagonia-5004';
update stone_materials set source_product_id = 5005, updated_at = current_timestamp where slug = 'noir-galaxy-5005';
update stone_materials set source_product_id = 5006, updated_at = current_timestamp where slug = 'noir-absolu-5006';
update stone_materials set source_product_id = 5007, updated_at = current_timestamp where slug = 'new-halayeb-5007';
update stone_materials set source_product_id = 5008, updated_at = current_timestamp where slug = 'matrix-titanium-5008';
update stone_materials set source_product_id = 5009, updated_at = current_timestamp where slug = 'labrador-noir-5009';
update stone_materials set source_product_id = 5010, updated_at = current_timestamp where slug = 'labrador-bleu-5010';
update stone_materials set source_product_id = 5011, updated_at = current_timestamp where slug = 'blanc-perle-5011';
update stone_materials set source_product_id = 5012, updated_at = current_timestamp where slug = 'baltic-brown-5012';
update stone_materials set source_product_id = 5014, updated_at = current_timestamp where slug = 'onyx-rose';
update stone_materials set source_product_id = 5015, updated_at = current_timestamp where slug = 'onyx-orange-5015';
update stone_materials set source_product_id = 5016, updated_at = current_timestamp where slug = 'onyx-marron-5016';
update stone_materials set source_product_id = 5017, updated_at = current_timestamp where slug = 'onyx-blue-5017';
update stone_materials set source_product_id = 5018, updated_at = current_timestamp where slug = 'onyx-blanc-5018';
update stone_materials set source_product_id = 5019, updated_at = current_timestamp where slug = 'vert-guatemala';
update stone_materials set source_product_id = 5020, updated_at = current_timestamp where slug = 'vert-des-alpes-5020';
update stone_materials set source_product_id = 5021, updated_at = current_timestamp where slug = 'tundra-gris-5021';
update stone_materials set source_product_id = 5024, updated_at = current_timestamp where slug = 'rouge-alicante-5024';
update stone_materials set source_product_id = 5025, updated_at = current_timestamp where slug = 'pierre-de-bali-5025';
update stone_materials set source_product_id = 5026, updated_at = current_timestamp where slug = 'perlatino-5026';
update stone_materials set source_product_id = 5027, updated_at = current_timestamp where slug = 'panda-white-5027';
update stone_materials set source_product_id = 5028, updated_at = current_timestamp where slug = 'noir-portoro-5028';
update stone_materials set source_product_id = 5029, updated_at = current_timestamp where slug = 'noir-flower-5029';
update stone_materials set source_product_id = 5030, updated_at = current_timestamp where slug = 'noir-aziza-5030';
update stone_materials set source_product_id = 5031, updated_at = current_timestamp where slug = 'marron-imperial-clair-5031';
update stone_materials set source_product_id = 5032, updated_at = current_timestamp where slug = 'marron-imperial-5032';
update stone_materials set source_product_id = 5033, updated_at = current_timestamp where slug = 'marmara-white-5033';
update stone_materials set source_product_id = 5034, updated_at = current_timestamp where slug = 'gris-armani-5034';
update stone_materials set source_product_id = 5035, updated_at = current_timestamp where slug = 'forest-vert-5035';
update stone_materials set source_product_id = 5036, updated_at = current_timestamp where slug = 'emotion-grey-5036';
update stone_materials set source_product_id = 5037, updated_at = current_timestamp where slug = 'deep-blue-5037';
update stone_materials set source_product_id = 5038, updated_at = current_timestamp where slug = 'crema-sofita-5038';
update stone_materials set source_product_id = 5039, updated_at = current_timestamp where slug = 'crema-royal-5039';
update stone_materials set source_product_id = 5040, updated_at = current_timestamp where slug = 'crema-marfil-5040';
update stone_materials set source_product_id = 5041, updated_at = current_timestamp where slug = 'crema-galala-5041';
update stone_materials set source_product_id = 5042, updated_at = current_timestamp where slug = 'calacatta-violia-5042';
update stone_materials set source_product_id = 5043, updated_at = current_timestamp where slug = 'blanc-thassos-5043';
update stone_materials set source_product_id = 5044, updated_at = current_timestamp where slug = 'blanc-polaris-5044';
update stone_materials set source_product_id = 5045, updated_at = current_timestamp where slug = 'blanc-ibiza-5045';
update stone_materials set source_product_id = 5046, updated_at = current_timestamp where slug = 'balnc-safir-5046';
update stone_materials set source_product_id = 5047, updated_at = current_timestamp where slug = 'blanc-carrare-5047';
update stone_materials set source_product_id = 5048, updated_at = current_timestamp where slug = 'volakas-5048';
update stone_materials set source_product_id = 5049, updated_at = current_timestamp where slug = 'arabiscato-orobico-rosso-5049';
update stone_materials set source_product_id = 5050, updated_at = current_timestamp where slug = 'arabiscato-orobico-5050';
update stone_materials set source_product_id = 5051, updated_at = current_timestamp where slug = 'arabiscato-blanc-5051';
update stone_materials set source_product_id = 5054, updated_at = current_timestamp where slug = 'onyx-vert-5054';
update stone_materials set source_product_id = 5055, updated_at = current_timestamp where slug = 'gris-khenifra-5055';
update stone_materials set source_product_id = 5056, updated_at = current_timestamp where slug = 'gris-msoun-5056';
update stone_materials set source_product_id = 5057, updated_at = current_timestamp where slug = 'volubilis-fonce-5057';
update stone_materials set source_product_id = 5058, updated_at = current_timestamp where slug = 'blanc-zayane-5058';

alter table catalogue_categories add constraint uk_catalogue_categories_source_category_id unique (source_category_id);
alter table stone_materials add constraint uk_stone_materials_source_product_id unique (source_product_id);

