create table order_addresses (
    id bigint generated by default as identity primary key,
    order_id bigint not null references customer_orders(id),
    type varchar(20) not null,
    recipient_name varchar(180) not null,
    company_name varchar(180),
    phone varchar(50),
    address_line1 varchar(220) not null,
    address_line2 varchar(220),
    city varchar(120) not null,
    region varchar(120),
    postal_code varchar(32),
    country_code varchar(2) not null
);
create index idx_order_addresses_order on order_addresses(order_id);
