create table website_quote_requests (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone not null,
  updated_at timestamp with time zone not null,
  reference_number varchar(48) not null unique,
  full_name varchar(160) not null,
  email varchar(320) not null,
  phone varchar(50) not null,
  company_name varchar(180),
  project_type varchar(100),
  city varchar(120),
  material_name varchar(180),
  material_slug varchar(180),
  quantity_m2 numeric(19,2),
  message varchar(2000),
  desired_date date,
  language varchar(8) not null,
  source varchar(80) not null,
  status varchar(20) not null
);
create index idx_website_quote_requests_status_created on website_quote_requests(status, created_at);
