create table customer_addresses (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone not null,
  updated_at timestamp with time zone not null,
  customer_id bigint not null references app_users(id),
  label varchar(100) not null,
  recipient_name varchar(180) not null,
  phone varchar(50),
  line1 varchar(220) not null,
  line2 varchar(220),
  city varchar(120) not null,
  region varchar(120),
  postal_code varchar(32),
  country varchar(100) not null,
  default_delivery boolean not null default false
);
create index idx_customer_addresses_customer on customer_addresses(customer_id);

create table customer_projects (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone not null,
  updated_at timestamp with time zone not null,
  customer_id bigint not null references app_users(id),
  name varchar(180) not null,
  project_type varchar(100),
  site_city varchar(120),
  site_address varchar(500),
  notes varchar(2000)
);
create index idx_customer_projects_customer on customer_projects(customer_id);
alter table quote_requests add column project_id bigint references customer_projects(id);

create table rfq_attachments (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone not null,
  updated_at timestamp with time zone not null,
  request_id bigint not null references quote_requests(id),
  original_filename varchar(255) not null,
  content_type varchar(120) not null,
  size_bytes bigint not null,
  storage_key varchar(255) not null unique,
  uploaded_by bigint not null references app_users(id)
);
create index idx_rfq_attachments_request on rfq_attachments(request_id);

create table audit_events (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone not null,
  updated_at timestamp with time zone not null,
  actor_id bigint references app_users(id),
  action varchar(100) not null,
  entity_type varchar(80) not null,
  entity_id bigint,
  detail varchar(2000)
);
create index idx_audit_events_entity on audit_events(entity_type, entity_id, created_at);
