create table catalogue_categories (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone not null,
  updated_at timestamp with time zone not null,
  slug varchar(120) not null unique,
  name varchar(100) not null unique,
  display_order integer not null,
  local_material boolean not null default false,
  active boolean not null default true
);

create table stone_material_images (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone not null,
  updated_at timestamp with time zone not null,
  material_id bigint not null references stone_materials(id) on delete cascade,
  image_url varchar(1000) not null,
  alt_text varchar(300),
  display_order integer not null default 0,
  primary_image boolean not null default false,
  unique (material_id, image_url)
);

create index idx_stone_material_images_material_order
  on stone_material_images(material_id, display_order);
