package com.univmar.purchasing;

import com.univmar.catalog.domain.*;
import com.univmar.common.api.ApiException;
import com.univmar.inventory.InventoryService;
import com.univmar.inventory.api.InventoryDtos.ReceiptInput;
import com.univmar.inventory.api.InventoryDtos.InventorySummary;
import com.univmar.inventory.domain.MovementType;
import com.univmar.purchasing.api.PurchaseOrderDtos.*;
import com.univmar.purchasing.domain.*;
import com.univmar.supplier.domain.*;
import java.math.BigDecimal;
import java.time.Year;
import java.util.*;
import org.springframework.data.domain.*;
import org.springframework.data.jpa.domain.Specification;
import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

@Service @Transactional
public class PurchaseOrderService {
    private final PurchaseOrderRepository orders; private final PurchaseOrderItemRepository items; private final GoodsReceiptRepository receipts; private final SupplierRepository suppliers; private final StoneVariantRepository variants; private final InventoryService inventory;
    public PurchaseOrderService(PurchaseOrderRepository orders, PurchaseOrderItemRepository items, GoodsReceiptRepository receipts, SupplierRepository suppliers, StoneVariantRepository variants, InventoryService inventory) { this.orders = orders; this.items = items; this.receipts = receipts; this.suppliers = suppliers; this.variants = variants; this.inventory = inventory; }
    public PurchaseOrderDetail create(PurchaseOrderInput input) { Supplier supplier = supplier(input.supplierId()); requireActive(supplier); PurchaseOrder order = orders.save(new PurchaseOrder(nextNumber(), supplier, input.expectedArrival(), trim(input.notes()))); order.replaceItems(buildItems(order, input.items())); return detail(order); }
    public PurchaseOrderDetail update(UUID id, PurchaseOrderInput input) { PurchaseOrder order = order(id); requireDraft(order); Supplier supplier = supplier(input.supplierId()); requireActive(supplier); order.update(supplier, input.expectedArrival(), trim(input.notes())); order.replaceItems(buildItems(order, input.items())); return detail(order); }
    @Transactional(readOnly = true) public PurchaseOrderDetail detail(UUID id) { return detail(order(id)); }
    @Transactional(readOnly = true) public PurchaseOrderPage list(String search, UUID supplierId, PurchaseOrderStatus status, Pageable pageable) { Specification<PurchaseOrder> spec = Specification.where(null); if (search != null && !search.isBlank()) { String value = "%" + search.trim().toLowerCase(Locale.ROOT) + "%"; spec = spec.and((root, query, cb) -> cb.or(cb.like(cb.lower(root.get("number")), value), cb.like(cb.lower(root.join("supplier").get("name")), value))); } if (supplierId != null) spec = spec.and((root, query, cb) -> cb.equal(root.get("supplier").get("id"), supplierId)); if (status != null) spec = spec.and((root, query, cb) -> cb.equal(root.get("status"), status)); return PurchaseOrderPage.from(orders.findAll(spec, pageable).map(this::summary)); }
    public PurchaseOrderDetail send(UUID id) { PurchaseOrder order = order(id); if (order.getStatus() != PurchaseOrderStatus.DRAFT) throw state("Only draft purchase orders can be sent."); order.setStatus(PurchaseOrderStatus.SENT); return detail(order); }
    public PurchaseOrderDetail confirm(UUID id) { PurchaseOrder order = order(id); if (!EnumSet.of(PurchaseOrderStatus.DRAFT, PurchaseOrderStatus.SENT).contains(order.getStatus())) throw state("Only draft or sent purchase orders can be confirmed."); order.setStatus(PurchaseOrderStatus.CONFIRMED); return detail(order); }
    public PurchaseOrderDetail cancel(UUID id) { PurchaseOrder order = order(id); if (EnumSet.of(PurchaseOrderStatus.RECEIVED, PurchaseOrderStatus.CANCELLED).contains(order.getStatus()) || order.getItems().stream().anyMatch(item -> item.getReceivedM2().signum() > 0)) throw state("A purchase order with received goods cannot be cancelled."); order.setStatus(PurchaseOrderStatus.CANCELLED); return detail(order); }
    public PurchaseOrderDetail receive(UUID orderId, ReceiveGoodsInput input) { PurchaseOrder order = order(orderId); if (!EnumSet.of(PurchaseOrderStatus.CONFIRMED, PurchaseOrderStatus.PARTIALLY_RECEIVED).contains(order.getStatus())) throw state("Confirm the purchase order before receiving goods."); PurchaseOrderItem item = items.findByIdAndPurchaseOrderId(input.itemId(), orderId).orElseThrow(() -> new ApiException(HttpStatus.NOT_FOUND, "PURCHASE_ORDER_ITEM_NOT_FOUND", "Purchase order item was not found.")); if (item.getRemainingM2().compareTo(input.quantityM2()) < 0) throw new ApiException(HttpStatus.CONFLICT, "RECEIPT_EXCEEDS_REMAINING", "The receipt quantity exceeds the remaining ordered quantity."); BigDecimal cost = input.costPerM2() == null ? item.getCostPerM2() : input.costPerM2(); InventorySummary received = inventory.receivePurchaseOrder(new ReceiptInput(item.getVariant().getId(), input.warehouseId(), input.locationId(), trim(input.lotNumber()), trim(input.bundleNumber()), input.quantityM2(), cost, order.getSupplier().getName(), java.time.LocalDate.now(), MovementType.PURCHASE_RECEIPT, trim(input.comment())), order.getNumber(), order.getSupplier().getName()); item.receive(input.quantityM2()); receipts.save(new GoodsReceipt(item, null, input.quantityM2(), trim(input.comment()))); order.setStatus(order.getItems().stream().allMatch(line -> line.getRemainingM2().signum() == 0) ? PurchaseOrderStatus.RECEIVED : PurchaseOrderStatus.PARTIALLY_RECEIVED); return detail(order); }
    private List<PurchaseOrderItem> buildItems(PurchaseOrder order, List<PurchaseItemInput> inputs) { Set<UUID> seen = new HashSet<>(); return inputs.stream().map(input -> { if (!seen.add(input.variantId())) throw new ApiException(HttpStatus.BAD_REQUEST, "DUPLICATE_PURCHASE_VARIANT", "A variant may appear only once on a purchase order."); StoneVariant variant = variants.findById(input.variantId()).orElseThrow(() -> new ApiException(HttpStatus.NOT_FOUND, "VARIANT_NOT_FOUND", "Material variant was not found.")); if (!variant.isActive()) throw state("Inactive variants cannot be ordered."); return new PurchaseOrderItem(order, variant, input.orderedM2(), input.costPerM2(), trim(input.notes())); }).toList(); }
    private PurchaseOrderSummary summary(PurchaseOrder order) { BigDecimal ordered = order.getItems().stream().map(PurchaseOrderItem::getOrderedM2).reduce(BigDecimal.ZERO, BigDecimal::add); BigDecimal received = order.getItems().stream().map(PurchaseOrderItem::getReceivedM2).reduce(BigDecimal.ZERO, BigDecimal::add); return new PurchaseOrderSummary(order.getId(), order.getNumber(), order.getSupplier().getId(), order.getSupplier().getName(), order.getStatus(), order.getExpectedArrival(), ordered, received); }
    private PurchaseOrderDetail detail(PurchaseOrder order) { return new PurchaseOrderDetail(order.getId(), order.getNumber(), order.getSupplier().getId(), order.getSupplier().getName(), order.getStatus(), order.getExpectedArrival(), order.getNotes(), order.getItems().stream().map(item -> { StoneVariant variant = item.getVariant(); StoneMaterial material = variant.getMaterial(); return new PurchaseItemResponse(item.getId(), variant.getId(), material.getName(), material.getSku(), variant.getThicknessMm(), variant.getFinish(), variant.getFormat(), item.getOrderedM2(), item.getReceivedM2(), item.getRemainingM2(), item.getCostPerM2(), item.getNotes(), receipts.findAllByPurchaseOrderItemIdOrderByReceivedAtDesc(item.getId()).stream().map(receipt -> new ReceiptResponse(receipt.getId(), receipt.getQuantityM2(), receipt.getReceivedAt(), receipt.getNote())).toList()); }).toList()); }
    private String nextNumber() { return "PO-" + Year.now().getValue() + "-" + String.format("%04d", orders.count() + 1); }
    private PurchaseOrder order(UUID id) { return orders.findById(id).orElseThrow(() -> new ApiException(HttpStatus.NOT_FOUND, "PURCHASE_ORDER_NOT_FOUND", "Purchase order was not found.")); } private Supplier supplier(UUID id) { return suppliers.findById(id).orElseThrow(() -> new ApiException(HttpStatus.NOT_FOUND, "SUPPLIER_NOT_FOUND", "Supplier was not found.")); } private void requireActive(Supplier supplier) { if (!supplier.isActive()) throw state("Inactive suppliers cannot be used on a purchase order."); } private void requireDraft(PurchaseOrder order) { if (order.getStatus() != PurchaseOrderStatus.DRAFT) throw state("Only draft purchase orders can be edited."); } private ApiException state(String message) { return new ApiException(HttpStatus.CONFLICT, "INVALID_PURCHASE_ORDER_STATE", message); } private String trim(String value) { return value == null || value.isBlank() ? null : value.trim(); }
}
