"use client";

import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { useLocalePath } from "@/lib/i18n";
import { readSavedMaterials, savedMaterialEvents, toggleSavedMaterial, type SavedMaterial } from "@/lib/favourites";

type Variant = { id: string; name: string; thicknessMm: number; format: string | null; availability: { code: string; label: string } };
export type DiscoveryProduct = { id: string; materialId: string; materialName: string; name: string; images: string; category: { name: string }; color?: string | null; origin?: string | null; applications?: string | null; recommendedUses?: string[]; careSummary?: string | null; indoorOutdoor?: string | null; variants: Variant[]; availability: { code: string; label: string } };

const useChoices = ["Kitchen worktop", "Floor", "Bathroom", "Stairs", "Facade", "Outdoor space"];

export default function CatalogueDiscoveryTools({ products }: { products: DiscoveryProduct[] }) {
  const localePath = useLocalePath();
  const [saved, setSaved] = useState<SavedMaterial[]>([]); const [mode, setMode] = useState<"selection" | "compare" | "finder" | null>(null);
  const [use, setUse] = useState(""); const [colour, setColour] = useState(""); const [setting, setSetting] = useState(""); const [area, setArea] = useState(""); const [showroom, setShowroom] = useState(false);
  useEffect(() => { const sync = () => setSaved(readSavedMaterials()); sync(); return savedMaterialEvents(sync); }, []);
  const selected = products.flatMap((product) => product.variants.map((variant) => ({ product, variant }))).filter(({ variant }) => saved.some((item) => item.variantId === variant.id));
  const results = useMemo(() => products.map((product) => {
    const uses = (product.recommendedUses?.length ? product.recommendedUses : product.applications?.split(/[,;\n]/) ?? []).join(" ").toLowerCase();
    const score = (use && uses.includes(use.toLowerCase()) ? 3 : 0) + (colour && `${product.color ?? ""} ${product.name}`.toLowerCase().includes(colour.toLowerCase()) ? 2 : 0) + (setting && (product.indoorOutdoor ?? "").toLowerCase().includes(setting.toLowerCase()) ? 2 : 0) + (showroom && product.availability.code === "SHOWROOM_SELECTION" ? 2 : 0);
    return { product, score };
  }).filter(({ product, score }) => score > 0 || (!use && !colour && !setting && !showroom)).sort((a, b) => b.score - a.score).slice(0, 6), [products, use, colour, setting, showroom]);
  const messageHref = `${localePath("/contact")}?intent=project&product=${encodeURIComponent(selected.map(({ product, variant }) => `${product.materialName} — ${variant.name}`).join(", "))}&productIds=${encodeURIComponent(selected.map(({ product }) => product.materialId).join(","))}&variantIds=${encodeURIComponent(selected.map(({ variant }) => variant.id).join(","))}`;
  return <>
    {!mode && <div className="catalog-discovery-toolbar">
      <button type="button" onClick={() => setMode("finder")}>Find my stone</button>
      <button type="button" onClick={() => setMode("selection")}>My selection{saved.length ? ` (${saved.length})` : ""}</button>
      {saved.length >= 2 && <button type="button" onClick={() => setMode("compare")}>Compare {Math.min(saved.length, 3)}</button>}
    </div>}
    {mode && <div className="discovery-sheet" role="dialog" aria-modal="true" aria-label={mode === "finder" ? "Find my stone" : mode === "compare" ? "Compare materials" : "My material selection"}><button className="discovery-sheet__backdrop" aria-label="Close" onClick={() => setMode(null)} /><section className="discovery-sheet__panel">
      <button type="button" className="discovery-sheet__close" onClick={() => setMode(null)}>×</button>
      {mode === "selection" && <><p className="eyebrow">YOUR MATERIAL SELECTION</p><h2>Save the stones you want to discuss</h2>{selected.length ? <div className="discovery-selection-list">{selected.map(({ product, variant }) => <div key={variant.id}><img src={product.images} alt="" /><span><b>{variant.name}</b><small>{product.materialName} · {variant.availability.label}</small></span><button type="button" onClick={() => toggleSavedMaterial({ productId: product.materialId, variantId: variant.id, name: product.materialName, variantName: variant.name, category: product.category.name, image: product.images, addedAt: "" })}>Remove</button></div>)}</div> : <p>Add materials from the catalogue or product pages. Your selection stays in this browser.</p>}<div className="discovery-sheet__actions">{selected.length >= 2 && <button onClick={() => setMode("compare")}>Compare selection</button>}{selected.length > 0 && <Link className="btn-gold" href={messageHref}>Send my selection to UNIVMAR</Link>}</div></>}
      {mode === "compare" && <><p className="eyebrow">MATERIAL COMPARISON</p><h2>Compare your selected stones</h2>{selected.length < 2 ? <p>Add at least two materials before comparing them.</p> : <div className="discovery-compare"><div className="discovery-compare__row"><b>Variant</b>{selected.slice(0,3).map(({ product, variant }) => <span key={variant.id}><img src={product.images} alt="" />{variant.name}<small>{product.materialName}</small></span>)}</div>{[["Material", ({product}: any) => product.materialName], ["Origin", ({product}: any) => product.origin ?? "To confirm"], ["Colour", ({product}: any) => product.color ?? "To confirm"], ["Thickness", ({variant}: any) => `${variant.thicknessMm} mm`], ["Recommended use", ({product}: any) => product.recommendedUses?.join(", ") || product.applications || "To confirm"], ["Care", ({product}: any) => product.careSummary || "Advice from our team"], ["Availability", ({variant}: any) => variant.availability.label]].map(([label, value]) => <div className="discovery-compare__row" key={label as string}><b>{label as string}</b>{selected.slice(0,3).map((item) => <span key={item.variant.id}>{(value as any)(item)}</span>)}</div>)}</div>}<Link href={messageHref} className="btn-gold">Request these materials</Link></>}
      {mode === "finder" && <><p className="eyebrow">STONE FINDER</p><h2>Tell us about your project</h2><p className="discovery-copy">Choose what matters for your project. We’ll show public catalogue options and your sales adviser confirms the final choice.</p><div className="finder-fields"><label>Where will it be used?<select value={use} onChange={(e) => setUse(e.target.value)}><option value="">Any use</option>{useChoices.map((option) => <option key={option}>{option}</option>)}</select></label><label>Colour preference<input value={colour} onChange={(e) => setColour(e.target.value)} placeholder="Warm beige, black, white…" /></label><label>Setting<select value={setting} onChange={(e) => setSetting(e.target.value)}><option value="">Interior or exterior</option><option>Interior</option><option>Exterior</option></select></label><label>Approximate area<input value={area} onChange={(e) => setArea(e.target.value)} placeholder="e.g. 18 m²" /></label><label className="finder-check"><input type="checkbox" checked={showroom} onChange={(e) => setShowroom(e.target.checked)} /> I want to select a physical slab</label></div><div className="finder-results">{results.map(({ product }) => { const variant = product.variants[0]; const item: SavedMaterial = { productId: product.materialId, variantId: variant?.id ?? product.id, name: product.materialName, variantName: variant?.name ?? product.name, category: product.category.name, image: product.images, addedAt: new Date().toISOString() }; const isSaved = saved.some((value) => value.variantId === item.variantId); return <article key={product.id}><img src={product.images} alt="" /><div><b>{product.name}</b><small>{product.materialName} · {product.availability.label}</small><p>Recommended for {use || "your project"}{colour ? ` and ${colour.toLowerCase()} tones` : ""}.</p></div><button type="button" onClick={() => { toggleSavedMaterial(item); setSaved(readSavedMaterials()); }}>{isSaved ? "Saved" : "Save"}</button></article>; })}</div>{selected.length > 0 && <Link href={`${messageHref}&finderUse=${encodeURIComponent(use)}&finderArea=${encodeURIComponent(area)}&showroom=${showroom}`} className="btn-gold">Send these recommendations</Link>}</>}
    </section></div>}
  </>;
}
