import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { createRoot } from "react-dom/client";
import { Archive, BarChart3, Boxes, ChevronRight, ClipboardList, FileText, ImagePlus, LayoutDashboard, LogOut, Menu, Package, Plus, Search, ShieldCheck, Users, X } from "lucide-react";
import { Button } from "./components/ui/button";
import { Badge } from "./components/ui/badge";
import { Card, CardContent, CardHeader } from "./components/ui/card";
import { Dialog, DialogContent, DialogTrigger } from "./components/ui/dialog";
import { Input } from "./components/ui/input";
import "./styles.css";

type View = "overview" | "catalogue" | "requests" | "quotations" | "orders" | "inventory" | "team";
type Category = { id: number; name: string; displayOrder: number; localMaterial?: boolean };
type Media = { id: number; url: string; primary: boolean; altText?: string };
type Variant = { id: number; finish: string; thicknessMm: number; indicativePrice: number | null; availability: string };
type Material = { id: number; name: string; slug: string; category: string; originCountry?: string; primaryColor?: string; description?: string; applications?: string; active: boolean; images: Media[]; variants: Variant[] };
type User = { id: number; email: string; role: string; status: string; createdAt: string };
type Draft = Omit<Material, "id" | "slug"> & { id?: number };
const newDraft = (category = ""): Draft => ({ name: "", category, originCountry: "", primaryColor: "", description: "", applications: "", active: true, images: [], variants: [] });
const modules: { id: View; label: string; icon: typeof LayoutDashboard; path?: string }[] = [
  { id: "overview", label: "Overview", icon: LayoutDashboard }, { id: "catalogue", label: "Catalogue", icon: Package }, { id: "requests", label: "Quote requests", icon: ClipboardList, path: "/sales/quote-requests" }, { id: "quotations", label: "Quotations", icon: FileText, path: "/sales/quotations" }, { id: "orders", label: "Orders", icon: Archive, path: "/sales/orders" }, { id: "inventory", label: "Inventory", icon: Boxes, path: "/inventory" }, { id: "team", label: "Team & access", icon: Users, path: "/admin/users" },
];
const sessionKey = "univmar.platform.access";
const jsonHeaders = { "Content-Type": "application/json" };
function slug(value: string) { return value.normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, ""); }
function label(value: unknown) { return typeof value === "string" ? value.replaceAll("_", " ") : String(value ?? "—"); }

function App() {
  const [token, setToken] = useState(sessionStorage.getItem(sessionKey) ?? "");
  const [email, setEmail] = useState(""); const [password, setPassword] = useState("");
  const [view, setView] = useState<View>("overview"); const [open, setOpen] = useState(false);
  const [materials, setMaterials] = useState<Material[]>([]); const [categories, setCategories] = useState<Category[]>([]); const [users, setUsers] = useState<User[]>([]);
  const [operations, setOperations] = useState<unknown[]>([]); const [draft, setDraft] = useState<Draft | null>(null); const [query, setQuery] = useState("");
  const [notice, setNotice] = useState(""); const [error, setError] = useState(""); const [loading, setLoading] = useState(false); const [sidebar, setSidebar] = useState(false);
  const request = useCallback(async (path: string, init: RequestInit = {}) => { const headers = new Headers(init.headers); headers.set("Authorization", `Bearer ${token}`); const response = await fetch(`/api/v1${path}`, { ...init, headers }); if (response.status === 401) { sessionStorage.removeItem(sessionKey); setToken(""); throw new Error("Your session ended. Sign in again."); } if (response.status === 403) throw new Error("Your account does not have access to this area."); return response; }, [token]);
  const loadCatalogue = useCallback(async () => { const [catalogueResponse, categoriesResponse] = await Promise.all([request("/admin/materials?size=500"), request("/materials/categories")]); if (!catalogueResponse.ok) throw new Error("Catalogue could not be loaded."); const page = await catalogueResponse.json() as { content?: Material[] }; setMaterials((page.content ?? []).sort((a, b) => a.name.localeCompare(b.name, "fr"))); if (categoriesResponse.ok) setCategories((await categoriesResponse.json() as Category[]).sort((a, b) => a.displayOrder - b.displayOrder)); }, [request]);
  const loadTeam = useCallback(async () => { const response = await request("/admin/users"); if (response.ok) setUsers(await response.json() as User[]); }, [request]);
  const loadOperations = useCallback(async (id: View) => { const module = modules.find((item) => item.id === id); if (!module?.path) return; const response = await request(module.path); if (!response.ok) throw new Error(`${module.label} could not be loaded.`); const body = await response.json() as unknown; setOperations(Array.isArray(body) ? body : (body && typeof body === "object" && "content" in body ? ((body as { content?: unknown[] }).content ?? []) : [body])); }, [request]);
  useEffect(() => { if (!token) return; setLoading(true); Promise.all([loadCatalogue(), loadTeam()]).catch((reason: unknown) => setError(reason instanceof Error ? reason.message : "Unable to load platform data.")).finally(() => setLoading(false)); }, [token, loadCatalogue, loadTeam]);
  useEffect(() => { if (token && !["overview", "catalogue", "team"].includes(view)) void loadOperations(view).catch((reason: unknown) => setError(reason instanceof Error ? reason.message : "Unable to load data.")); }, [token, view, loadOperations]);
  const signIn = async (event: FormEvent) => { event.preventDefault(); setLoading(true); setError(""); try { const response = await fetch("/api/v1/auth/login", { method: "POST", headers: jsonHeaders, body: JSON.stringify({ email, password }) }); if (!response.ok) throw new Error("Invalid email or password."); const body = await response.json() as { accessToken?: string }; if (!body.accessToken) throw new Error("Sign in is unavailable."); sessionStorage.setItem(sessionKey, body.accessToken); setToken(body.accessToken); setPassword(""); } catch (reason) { setError(reason instanceof Error ? reason.message : "Sign in failed."); } finally { setLoading(false); } };
  const saveProduct = async () => { if (!draft || !draft.name.trim() || !draft.category) return setError("Name and category are required."); setLoading(true); setError(""); try { const payload = { name: draft.name.trim(), slug: draft.id ? "unchanged" : slug(draft.name), category: draft.category, originCountry: draft.originCountry || null, primaryColor: draft.primaryColor || null, description: draft.description || null, applications: draft.applications || null, active: draft.active, images: draft.images.map((image) => ({ url: image.url, altText: image.altText ?? draft.name })) }; const response = await request(draft.id ? `/admin/materials/${draft.id}` : "/admin/materials", { method: draft.id ? "PUT" : "POST", headers: jsonHeaders, body: JSON.stringify(payload) }); if (!response.ok) throw new Error("Product could not be saved."); const saved = await response.json() as Material; setDraft(saved); await loadCatalogue(); setNotice("Product saved. Upload images below once it has been created."); } catch (reason) { setError(reason instanceof Error ? reason.message : "Product could not be saved."); } finally { setLoading(false); } };
  const upload = async (files: FileList | null) => { if (!files?.length || !draft?.id) return setError("Save the product before uploading images."); setLoading(true); try { const added: Media[] = []; for (const file of Array.from(files)) { const form = new FormData(); form.set("file", file); form.set("altText", draft.name); const response = await request(`/admin/materials/${draft.id}/images`, { method: "POST", body: form }); if (!response.ok) throw new Error("Use JPEG, PNG, or WebP files smaller than 10 MB."); added.push(await response.json() as Media); } setDraft({ ...draft, images: [...draft.images, ...added] }); await loadCatalogue(); setNotice("Image stored in platform media."); } catch (reason) { setError(reason instanceof Error ? reason.message : "Image could not be uploaded."); } finally { setLoading(false); } };
  const removeMedia = async (media: Media) => { if (!draft?.id || !confirm("Remove this image from the platform?")) return; const response = await request(`/admin/materials/${draft.id}/images/${media.id}`, { method: "DELETE" }); if (!response.ok) return setError("Image could not be removed."); setDraft({ ...draft, images: draft.images.filter((item) => item.id !== media.id) }); await loadCatalogue(); };
  const hideProduct = async () => { if (!draft?.id || !confirm("Hide this product from the landing site?")) return; const response = await request(`/admin/materials/${draft.id}`, { method: "DELETE" }); if (!response.ok) return setError("Product could not be hidden."); setDraft(null); await loadCatalogue(); setNotice("Product is hidden from the landing site."); };
  const updateUser = async (user: User, role: string, active: boolean) => { const response = await request(`/admin/users/${user.id}`, { method: "PATCH", headers: jsonHeaders, body: JSON.stringify({ role, active }) }); if (!response.ok) return setError("Access could not be updated."); await loadTeam(); setNotice("User access updated."); };
  const visibleMaterials = useMemo(() => materials.filter((item) => `${item.name} ${item.category}`.toLowerCase().includes(query.toLowerCase())), [materials, query]);
  if (!token) return <SignIn email={email} password={password} loading={loading} error={error} setEmail={setEmail} setPassword={setPassword} onSubmit={signIn} />;
  return <div className="min-h-screen bg-[#f7f7f4] text-stone-900"><aside className={`sidebar ${sidebar ? "open" : ""}`}><div className="brand"><div className="brandmark">U</div><div><b>UNIVMAR</b><span>Operations platform</span></div><button className="mobile-close" onClick={() => setSidebar(false)}><X size={18}/></button></div><nav>{modules.map((item) => { const Icon = item.icon; return <button key={item.id} className={view === item.id ? "active" : ""} onClick={() => { setView(item.id); setSidebar(false); }}><Icon size={17}/>{item.label}</button>; })}</nav><div className="sidefoot"><ShieldCheck size={16}/><span>Role-protected workspace</span></div></aside><main className="dashboard"><header className="topbar"><Button variant="ghost" className="mobile-menu" onClick={() => setSidebar(true)}><Menu size={19}/></Button><div className="crumb"><span>Workspace</span><ChevronRight size={15}/><b>{modules.find((item) => item.id === view)?.label}</b></div><div className="top-actions"><Badge className="hidden sm:inline-flex">Secure session</Badge><Button variant="outline" size="sm" onClick={() => { sessionStorage.removeItem(sessionKey); setToken(""); }}><LogOut size={15}/>Sign out</Button></div></header><section className="page">{error && <Alert kind="error" text={error} close={() => setError("")} />}{notice && <Alert kind="notice" text={notice} close={() => setNotice("")} />}{loading && <div className="loadingbar" />}{view === "overview" && <Overview materials={materials} users={users} onCatalog={() => setView("catalogue")} />}{view === "catalogue" && <Catalogue materials={visibleMaterials} categories={categories} query={query} setQuery={setQuery} draft={draft} setDraft={setDraft} save={saveProduct} upload={upload} removeMedia={removeMedia} hide={hideProduct} loading={loading} />}{view === "team" && <Team users={users} update={updateUser} />}{!["overview", "catalogue", "team"].includes(view) && <Operations title={modules.find((item) => item.id === view)?.label ?? "Operations"} rows={operations} />}</section></main></div>;
}

function SignIn({ email, password, loading, error, setEmail, setPassword, onSubmit }: { email: string; password: string; loading: boolean; error: string; setEmail(value: string): void; setPassword(value: string): void; onSubmit(event: FormEvent): void }) { return <main className="signin-shell"><form className="signin-card" onSubmit={onSubmit}><div className="brandmark">U</div><p className="eyebrow">UNIVMAR PLATFORM</p><h1>Control room for stone operations.</h1><p className="muted">Use your platform administrator account. The session is kept only for this browser tab.</p><label>Work email<Input type="email" value={email} onChange={(event) => setEmail(event.target.value)} autoComplete="username" required /></label><label>Password<Input type="password" value={password} onChange={(event) => setPassword(event.target.value)} autoComplete="current-password" required /></label><Button className="w-full" disabled={loading}>{loading ? "Signing in…" : "Sign in securely"}</Button>{error && <p className="signin-error">{error}</p>}</form></main>; }
function Alert({ kind, text, close }: { kind: "error" | "notice"; text: string; close(): void }) { return <div className={`alert ${kind}`}><span>{text}</span><button onClick={close}><X size={15}/></button></div>; }
function Overview({ materials, users, onCatalog }: { materials: Material[]; users: User[]; onCatalog(): void }) { const live = materials.filter((item) => item.active).length; const media = materials.reduce((sum, item) => sum + item.images.length, 0); return <><div className="page-title"><div><p className="eyebrow">OPERATIONS SNAPSHOT</p><h1>Today’s catalogue pulse</h1><p className="muted">A clear view of what is live, ready for quotation, and owned by your team.</p></div><Button onClick={onCatalog}><Plus size={16}/>Manage catalogue</Button></div><div className="metric-grid"><Metric label="Live materials" value={live} note={`${materials.length - live} hidden`} icon={<Package/>}/><Metric label="Product media" value={media} note="stored outside source control" icon={<ImagePlus/>}/><Metric label="Team accounts" value={users.length} note={`${users.filter((user) => user.status === "ACTIVE").length} active`} icon={<Users/>}/><Metric label="Commercial workflow" value="Ready" note="RFQ → quotation → order" icon={<BarChart3/>}/></div><div className="overview-grid"><Card><CardHeader><b>Catalogue readiness</b><span className="card-sub">Products visible to the landing website</span></CardHeader><CardContent><div className="quarry-meter"><div style={{ width: `${materials.length ? Math.round((live / materials.length) * 100) : 0}%` }}/></div><div className="meter-label"><span>{live} of {materials.length} published</span><b>{materials.length ? Math.round((live / materials.length) * 100) : 0}%</b></div><p className="muted mt-5">Published products are immediately returned by the public catalogue API. Product images are served from persistent platform media, never from GitHub.</p></CardContent></Card><Card><CardHeader><b>Operating sequence</b></CardHeader><CardContent><ol className="sequence"><li><i>01</i><div><b>Qualify request</b><span>Review customer RFQs and project requirements.</span></div></li><li><i>02</i><div><b>Send quotation</b><span>Turn approved material selections into a commercial offer.</span></div></li><li><i>03</i><div><b>Reserve and fulfil</b><span>Accept, reserve inventory, and progress the order.</span></div></li></ol></CardContent></Card></div></> }
function Metric({ label, value, note, icon }: { label: string; value: string | number; note: string; icon: React.ReactNode }) { return <Card className="metric"><CardContent><div className="metric-icon">{icon}</div><p>{label}</p><b>{value}</b><span>{note}</span></CardContent></Card>; }
function Catalogue({ materials, categories, query, setQuery, draft, setDraft, save, upload, removeMedia, hide, loading }: { materials: Material[]; categories: Category[]; query: string; setQuery(value: string): void; draft: Draft | null; setDraft(value: Draft | null): void; save(): void; upload(files: FileList | null): void; removeMedia(media: Media): void; hide(): void; loading: boolean }) { return <><div className="page-title"><div><p className="eyebrow">PUBLIC CATALOGUE</p><h1>Materials and media</h1><p className="muted">Every published item is shown on the landing website from the platform API.</p></div><Dialog><DialogTrigger asChild><Button onClick={() => setDraft(newDraft(categories[0]?.name ?? ""))}><Plus size={16}/>New material</Button></DialogTrigger><DialogContent className="max-w-4xl"><Editor draft={draft} categories={categories} setDraft={setDraft} save={save} upload={upload} removeMedia={removeMedia} hide={hide} loading={loading}/></DialogContent></Dialog></div><Card><CardHeader className="catalogue-head"><div><b>Material library</b><span className="card-sub">{materials.length} matching materials</span></div><div className="search"><Search size={16}/><Input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search material or category" /></div></CardHeader><div className="data-table"><table><thead><tr><th>Material</th><th>Category</th><th>Media</th><th>Visibility</th><th></th></tr></thead><tbody>{materials.map((material) => <tr key={material.id}><td><div className="material-cell">{material.images[0] ? <img src={material.images[0].url} alt=""/> : <div className="image-empty"/>}<div><b>{material.name}</b><span>#{material.id} · {material.slug}</span></div></div></td><td>{material.category}</td><td>{material.images.length} files</td><td><Badge className={material.active ? "badge-live" : "badge-hidden"}>{material.active ? "Published" : "Hidden"}</Badge></td><td><Dialog><DialogTrigger asChild><Button variant="ghost" size="sm" onClick={() => setDraft(material)}>Edit</Button></DialogTrigger><DialogContent className="max-w-4xl"><Editor draft={draft} categories={categories} setDraft={setDraft} save={save} upload={upload} removeMedia={removeMedia} hide={hide} loading={loading}/></DialogContent></Dialog></td></tr>)}</tbody></table>{!materials.length && <p className="empty">No materials match this search.</p>}</div></Card></> }
function Editor({ draft, categories, setDraft, save, upload, removeMedia, hide, loading }: { draft: Draft | null; categories: Category[]; setDraft(value: Draft | null): void; save(): void; upload(files: FileList | null): void; removeMedia(media: Media): void; hide(): void; loading: boolean }) { if (!draft) return null; return <div className="editor"><div className="editor-title"><div><p className="eyebrow">MATERIAL RECORD</p><h2>{draft.id ? `Edit ${draft.name}` : "New material"}</h2></div><div>{draft.id && <Button variant="destructive" size="sm" onClick={hide}>Hide from landing</Button>}<Button className="ml-2" size="sm" onClick={save} disabled={loading}>Save changes</Button></div></div><div className="form-grid"><label>Name<Input value={draft.name} onChange={(event) => setDraft({ ...draft, name: event.target.value })}/></label><label>Category<select value={draft.category} onChange={(event) => setDraft({ ...draft, category: event.target.value })}>{categories.map((category) => <option key={category.id} value={category.name}>{category.name}</option>)}</select></label><label>Origin<Input value={draft.originCountry ?? ""} onChange={(event) => setDraft({ ...draft, originCountry: event.target.value })}/></label><label>Primary colour<Input value={draft.primaryColor ?? ""} onChange={(event) => setDraft({ ...draft, primaryColor: event.target.value })}/></label><label className="wide">Description<textarea value={draft.description ?? ""} onChange={(event) => setDraft({ ...draft, description: event.target.value })}/></label><label className="wide checkline"><input type="checkbox" checked={draft.active} onChange={(event) => setDraft({ ...draft, active: event.target.checked })}/>Publish to the landing website</label></div><div className="media-editor"><div><b>Product images</b><p className="muted">JPEG, PNG, or WebP · maximum 10 MB. Files are stored in the platform media volume.</p></div>{draft.id ? <label className="upload-control"><ImagePlus size={16}/>Upload media<input type="file" multiple accept="image/jpeg,image/png,image/webp" onChange={(event) => upload(event.target.files)}/></label> : <Badge>Save before uploading</Badge>}<div className="media-grid">{draft.images.map((media) => <figure key={media.id}><img src={media.url} alt={draft.name}/><button onClick={() => removeMedia(media)} aria-label="Remove image"><X size={15}/></button>{media.primary && <figcaption>Primary</figcaption>}</figure>)}</div></div></div> }
function Operations({ title, rows }: { title: string; rows: unknown[] }) { const list = rows.filter((row): row is Record<string, unknown> => Boolean(row) && typeof row === "object"); const fields = list.length ? Object.keys(list[0]).slice(0, 6) : []; return <><div className="page-title"><div><p className="eyebrow">COMMERCIAL OPERATIONS</p><h1>{title}</h1><p className="muted">Live records from the protected platform API.</p></div></div><Card><CardHeader><b>{list.length} records</b><span className="card-sub">Access is enforced by your assigned role.</span></CardHeader><div className="data-table"><table><thead><tr>{fields.map((field) => <th key={field}>{label(field)}</th>)}</tr></thead><tbody>{list.map((row, index) => <tr key={index}>{fields.map((field) => <td key={field}>{typeof row[field] === "object" ? JSON.stringify(row[field]) : label(row[field])}</td>)}</tr>)}</tbody></table>{!list.length && <p className="empty">No records are available for this workspace.</p>}</div></Card></> }
function Team({ users, update }: { users: User[]; update(user: User, role: string, active: boolean): void }) { return <><div className="page-title"><div><p className="eyebrow">ACCESS CONTROL</p><h1>Team & permissions</h1><p className="muted">Role-based access is verified by the API on every protected operation.</p></div></div><Card><div className="data-table"><table><thead><tr><th>User</th><th>Role</th><th>Status</th><th>Created</th><th></th></tr></thead><tbody>{users.map((user) => <tr key={user.id}><td><b>{user.email}</b></td><td><select defaultValue={user.role} onChange={(event) => update(user, event.target.value, user.status === "ACTIVE")}><option>ADMIN</option><option>SALES</option><option>INVENTORY_MANAGER</option><option>MANAGER</option><option>CUSTOMER</option></select></td><td><Badge className={user.status === "ACTIVE" ? "badge-live" : "badge-hidden"}>{user.status}</Badge></td><td>{new Date(user.createdAt).toLocaleDateString()}</td><td><Button size="sm" variant="outline" onClick={() => update(user, user.role, user.status !== "ACTIVE")}>{user.status === "ACTIVE" ? "Disable" : "Enable"}</Button></td></tr>)}</tbody></table></div></Card></> }
createRoot(document.getElementById("root")!).render(<App />);
