package com.univmar.rfq;
import com.univmar.catalog.domain.StoneVariantRepository; import com.univmar.customer.domain.CustomerProject; import com.univmar.customer.domain.CustomerProjectRepository; import com.univmar.rfq.api.RfqDtos; import com.univmar.rfq.domain.*; import com.univmar.shared.api.ApiException; import com.univmar.user.domain.Role; import com.univmar.user.domain.UserRepository; import java.util.List; import org.springframework.data.domain.Page; import org.springframework.data.domain.Pageable; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
@Service public class RfqService { private final QuoteRequestRepository requests; private final QuoteRequestItemRepository items; private final UserRepository users; private final StoneVariantRepository variants; private final CustomerProjectRepository projects; public RfqService(QuoteRequestRepository r,QuoteRequestItemRepository i,UserRepository u,StoneVariantRepository v,CustomerProjectRepository p){requests=r;items=i;users=u;variants=v;projects=p;}
 @Transactional public RfqDtos.Response create(Long customerId,RfqDtos.Create input){CustomerProject project=input.projectId()==null?null:projects.findByIdAndCustomerId(input.projectId(),customerId).orElseThrow(ApiException::forbidden); QuoteRequest request=requests.save(new QuoteRequest(users.findById(customerId).orElseThrow(()->ApiException.notFound("Customer")),project,input.notes(),input.desiredDate()));for(var item:input.items())items.save(new QuoteRequestItem(request,variants.findById(item.variantId()).orElseThrow(()->ApiException.notFound("Variant")),item.quantityM2(),item.note()));return new RfqDtos.Response(request.getId(),request.getStatus().name());}
 @Transactional public RfqDtos.Response submit(Long customerId,Long id){QuoteRequest request=owned(customerId,id);if(items.findByRequestId(id).isEmpty())throw ApiException.conflict("EMPTY_RFQ","RFQ must contain at least one item");try{request.submit();}catch(IllegalStateException e){throw ApiException.conflict("INVALID_STATE_TRANSITION",e.getMessage());}return new RfqDtos.Response(request.getId(),request.getStatus().name());}
 @Transactional(readOnly=true) public List<RfqDtos.Detail> mine(Long customerId){return requests.findByCustomerId(customerId).stream().map(this::detail).toList();}
 @Transactional(readOnly=true) public RfqDtos.Detail mineDetail(Long customerId,Long id){return detail(owned(customerId,id));}
 @Transactional(readOnly=true) public Page<RfqDtos.Detail> sales(Pageable pageable){return requests.findAll(pageable).map(this::detail);}
 @Transactional(readOnly=true) public RfqDtos.Detail salesDetail(Long id){return detail(find(id));}
 @Transactional public RfqDtos.Detail assignAndReview(Long id,Long salesUserId){QuoteRequest request=find(id);var sales=users.findById(salesUserId).orElseThrow(()->ApiException.notFound("Sales user"));if(sales.getRole()!=Role.SALES&&sales.getRole()!=Role.ADMIN)throw ApiException.conflict("INVALID_ASSIGNEE","Assignee must be a Sales user or Admin");try{request.review(salesUserId);}catch(IllegalStateException e){throw ApiException.conflict("INVALID_STATE_TRANSITION",e.getMessage());}return detail(request);}
 private QuoteRequest owned(Long customerId,Long id){QuoteRequest r=find(id);if(!r.getCustomer().getId().equals(customerId))throw ApiException.forbidden();return r;} private QuoteRequest find(Long id){return requests.findById(id).orElseThrow(()->ApiException.notFound("RFQ"));}
 private RfqDtos.Detail detail(QuoteRequest r){var lines=items.findByRequestId(r.getId()).stream().map(i->new RfqDtos.ItemDetail(i.getId(),i.getVariant().getId(),i.getVariant().getMaterial().getName(),i.getVariant().getFinish(),i.getQuantityM2(),i.getNote())).toList();return new RfqDtos.Detail(r.getId(),r.getStatus().name(),r.getCustomer().getId(),r.getProject()==null?null:r.getProject().getId(),r.getProject()==null?null:r.getProject().getName(),r.getNotes(),r.getDesiredDate(),r.getAssigneeId(),lines);}
}
