package com.univmar.fabrication;

import com.univmar.common.api.ApiException;
import com.univmar.fabrication.api.FabricationDtos.*;
import com.univmar.fabrication.domain.*;
import com.univmar.inventory.domain.InventoryItemRepository;
import com.univmar.order.domain.*;
import com.univmar.remnant.domain.StoneRemnantRepository;
import com.univmar.slab.domain.StoneSlabRepository;
import java.time.LocalDate;
import java.util.*;
import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

@Service
@Transactional
public class FabricationService {
    private final FabricationJobRepository jobs; private final FabricationOperationRepository operations; private final SalesOrderRepository orders; private final InventoryItemRepository inventory; private final StoneSlabRepository slabs; private final StoneRemnantRepository remnants;
    public FabricationService(FabricationJobRepository jobs, FabricationOperationRepository operations, SalesOrderRepository orders, InventoryItemRepository inventory, StoneSlabRepository slabs, StoneRemnantRepository remnants) { this.jobs = jobs; this.operations = operations; this.orders = orders; this.inventory = inventory; this.slabs = slabs; this.remnants = remnants; }
    public Response create(CreateInput input) { SalesOrder order = orders.findById(input.orderId()).orElseThrow(() -> notFound("ORDER_NOT_FOUND", "Order was not found.")); if (order.getStatus() == OrderStatus.CANCELLED || order.getStatus() == OrderStatus.DELIVERED) throw conflict("ORDER_NOT_FABRICATABLE", "Only an active order can receive a fabrication job."); FabricationJob job = new FabricationJob(nextNumber(), order, input.title().trim(), input.priority(), input.dueDate(), trim(input.measurementNotes()), trim(input.drawingUrl()), trim(input.notes())); List<OperationInput> requested = input.operations() == null || input.operations().isEmpty() ? List.of(new OperationInput(FabricationOperationType.CUTTING, null), new OperationInput(FabricationOperationType.QUALITY_CHECK, null)) : input.operations(); int sequence = 1; for (OperationInput operation : requested) job.addOperation(new FabricationOperation(job, operation.operationType(), sequence++, trim(operation.notes()))); order.event("FABRICATION_JOB_CREATED", "Fabrication job " + job.getJobNumber() + " created"); return response(jobs.save(job)); }
    @Transactional(readOnly = true) public List<Response> list(FabricationStatus status) { List<FabricationJob> list = status == null ? jobs.findAll() : jobs.findAllByStatus(status); return list.stream().sorted(Comparator.comparing(FabricationJob::getDueDate, Comparator.nullsLast(Comparator.naturalOrder())).thenComparing(FabricationJob::getCreatedAt)).map(this::response).toList(); }
    @Transactional(readOnly = true) public Response detail(UUID id) { return response(entity(id)); }
    public Response advance(UUID id, AdvanceInput input) { FabricationJob job = entity(id); if (input.status() == FabricationStatus.READY && job.getOperations().stream().anyMatch(operation -> operation.getStatus() != FabricationOperationStatus.COMPLETED)) throw conflict("OPERATIONS_PENDING", "Complete every workshop operation before marking a job ready."); try { job.advance(input.status()); } catch (IllegalStateException exception) { throw conflict("INVALID_FABRICATION_TRANSITION", "Advance the job one workshop stage at a time."); } job.getOrder().event("FABRICATION_STAGE_CHANGED", "Fabrication job " + job.getJobNumber() + " moved to " + input.status()); return response(job); }
    public Response addOperation(UUID id, OperationInput input) { FabricationJob job = entity(id); int nextSequence = job.getOperations().stream().mapToInt(FabricationOperation::getSequenceNo).max().orElse(0) + 1; job.addOperation(new FabricationOperation(job, input.operationType(), nextSequence, trim(input.notes()))); return response(job); }
    public Response completeOperation(UUID jobId, UUID operationId) { FabricationJob job = entity(jobId); FabricationOperation operation = operations.findById(operationId).orElseThrow(() -> notFound("OPERATION_NOT_FOUND", "Fabrication operation was not found.")); if (!operation.getJob().getId().equals(job.getId())) throw conflict("OPERATION_JOB_MISMATCH", "This operation does not belong to the fabrication job."); try { operation.complete(); } catch (IllegalStateException exception) { throw conflict("OPERATION_ALREADY_COMPLETED", "This operation is already completed."); } return response(job); }
    public Response assignMaterial(UUID id, MaterialInput input) { FabricationJob job = entity(id); if (job.getMaterials().stream().anyMatch(material -> material.getMaterialType() == input.materialType() && material.getMaterialId().equals(input.materialId()))) throw conflict("MATERIAL_ALREADY_ASSIGNED", "This material is already assigned to the job."); ensureMaterial(input.materialType(), input.materialId()); job.addMaterial(new FabricationMaterial(job, input.materialType(), input.materialId(), trim(input.notes()))); return response(job); }
    private void ensureMaterial(FabricationMaterialType type, UUID id) { boolean found = switch (type) { case INVENTORY_ITEM -> inventory.existsById(id); case SLAB -> slabs.existsById(id); case REMNANT -> remnants.existsById(id); }; if (!found) throw notFound("FABRICATION_MATERIAL_NOT_FOUND", "Selected material was not found."); }
    private FabricationJob entity(UUID id) { return jobs.findById(id).orElseThrow(() -> notFound("FABRICATION_JOB_NOT_FOUND", "Fabrication job was not found.")); }
    private Response response(FabricationJob job) { SalesOrder order = job.getOrder(); return new Response(job.getId(), job.getJobNumber(), order.getId(), order.getNumber(), order.getCustomer().getName(), order.getProject().getName(), job.getTitle(), job.getStatus(), job.getPriority(), job.getDueDate(), job.getMeasurementNotes(), job.getDrawingUrl(), job.getNotes(), job.getCreatedAt(), job.getReadyAt(), job.getOperations().stream().sorted(Comparator.comparingInt(FabricationOperation::getSequenceNo)).map(operation -> new Operation(operation.getId(), operation.getOperationType(), operation.getSequenceNo(), operation.getNotes(), operation.getStatus(), operation.getCompletedAt())).toList(), job.getMaterials().stream().map(this::material).toList()); }
    private Material material(FabricationMaterial material) { return switch (material.getMaterialType()) { case INVENTORY_ITEM -> { var item = inventory.findById(material.getMaterialId()).orElseThrow(); yield new Material(material.getId(), material.getMaterialType(), item.getId(), item.getVariant().getMaterial().getName(), item.getWarehouse().getName() + " / " + item.getLocation().getCode() + " · " + item.getAvailableM2() + " m²", material.getNotes()); } case SLAB -> { var slab = slabs.findById(material.getMaterialId()).orElseThrow(); yield new Material(material.getId(), material.getMaterialType(), slab.getId(), slab.getSlabNumber(), slab.getInventoryItem().getVariant().getMaterial().getName() + " · " + slab.getSurfaceAreaM2() + " m²", material.getNotes()); } case REMNANT -> { var remnant = remnants.findById(material.getMaterialId()).orElseThrow(); yield new Material(material.getId(), material.getMaterialType(), remnant.getId(), remnant.getRemnantNumber(), remnant.getParentSlab().getInventoryItem().getVariant().getMaterial().getName() + " · " + remnant.getSurfaceAreaM2() + " m²", material.getNotes()); } }; }
    private String nextNumber() { return "FAB-" + LocalDate.now().toString().replace("-", "") + "-" + UUID.randomUUID().toString().substring(0, 6).toUpperCase(Locale.ROOT); }
    private String trim(String value) { return value == null || value.isBlank() ? null : value.trim(); }
    private ApiException notFound(String code, String message) { return new ApiException(HttpStatus.NOT_FOUND, code, message); } private ApiException conflict(String code, String message) { return new ApiException(HttpStatus.CONFLICT, code, message); }
}
