package com.univmar.fabrication;

import com.univmar.common.api.ApiException;
import com.univmar.fabrication.api.FabricationDtos.*;
import com.univmar.fabrication.domain.*;
import com.univmar.inventory.domain.*;
import com.univmar.order.domain.*;
import com.univmar.remnant.domain.RemnantStatus;
import com.univmar.remnant.domain.StoneRemnantRepository;
import com.univmar.slab.domain.SlabStatus;
import com.univmar.slab.domain.StoneSlabRepository;
import java.math.BigDecimal;
import java.time.Instant;
import java.time.LocalDate;
import java.util.*;
import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

@Service
@Transactional
public class FabricationService {
    private final FabricationJobRepository jobs; private final FabricationOperationRepository operations; private final FabricationMaterialRepository materials; private final SalesOrderRepository orders; private final InventoryItemRepository inventory; private final StockMovementRepository movements; private final StoneSlabRepository slabs; private final StoneRemnantRepository remnants;
    public FabricationService(FabricationJobRepository jobs, FabricationOperationRepository operations, FabricationMaterialRepository materials, SalesOrderRepository orders, InventoryItemRepository inventory, StockMovementRepository movements, StoneSlabRepository slabs, StoneRemnantRepository remnants) { this.jobs = jobs; this.operations = operations; this.materials = materials; this.orders = orders; this.inventory = inventory; this.movements = movements; this.slabs = slabs; this.remnants = remnants; }
    public Response create(CreateInput input) { SalesOrder order = orders.findById(input.orderId()).orElseThrow(() -> notFound("ORDER_NOT_FOUND", "Order was not found.")); if (order.getStatus() == OrderStatus.CANCELLED || order.getStatus() == OrderStatus.DELIVERED) throw conflict("ORDER_NOT_FABRICATABLE", "Only an active order can receive a fabrication job."); FabricationJob job = new FabricationJob(nextNumber(), order, input.title().trim(), input.priority(), input.dueDate(), trim(input.measurementNotes()), trim(input.drawingUrl()), trim(input.notes())); List<OperationInput> requested = input.operations() == null || input.operations().isEmpty() ? List.of(new OperationInput(FabricationOperationType.CUTTING, null), new OperationInput(FabricationOperationType.QUALITY_CHECK, null)) : input.operations(); int sequence = 1; for (OperationInput operation : requested) job.addOperation(new FabricationOperation(job, operation.operationType(), sequence++, trim(operation.notes()))); order.event("FABRICATION_JOB_CREATED", "Fabrication job " + job.getJobNumber() + " created"); return response(jobs.save(job)); }
    @Transactional(readOnly = true) public List<Response> list(FabricationStatus status) { List<FabricationJob> list = status == null ? jobs.findAll() : jobs.findAllByStatus(status); return list.stream().sorted(Comparator.comparing(FabricationJob::getDueDate, Comparator.nullsLast(Comparator.naturalOrder())).thenComparing(FabricationJob::getCreatedAt)).map(this::response).toList(); }
    @Transactional(readOnly = true) public Response detail(UUID id) { return response(entity(id)); }
    public Response advance(UUID id, AdvanceInput input) { FabricationJob job = entity(id); ensureJobActive(job); if (input.status() == FabricationStatus.READY && job.getOperations().stream().anyMatch(operation -> operation.getStatus() != FabricationOperationStatus.COMPLETED)) throw conflict("OPERATIONS_PENDING", "Complete every workshop operation before marking a job ready."); try { job.advance(input.status()); } catch (IllegalStateException exception) { throw conflict("INVALID_FABRICATION_TRANSITION", "Advance the job one workshop stage at a time."); } if (input.status() == FabricationStatus.READY) consumeMaterials(job); job.getOrder().event("FABRICATION_STAGE_CHANGED", "Fabrication job " + job.getJobNumber() + " moved to " + input.status()); return response(job); }
    public Response addOperation(UUID id, OperationInput input) { FabricationJob job = entity(id); ensureJobActive(job); int nextSequence = job.getOperations().stream().mapToInt(FabricationOperation::getSequenceNo).max().orElse(0) + 1; job.addOperation(new FabricationOperation(job, input.operationType(), nextSequence, trim(input.notes()))); return response(job); }
    public Response completeOperation(UUID jobId, UUID operationId) { FabricationJob job = entity(jobId); ensureJobActive(job); FabricationOperation operation = operations.findById(operationId).orElseThrow(() -> notFound("OPERATION_NOT_FOUND", "Fabrication operation was not found.")); if (!operation.getJob().getId().equals(job.getId())) throw conflict("OPERATION_JOB_MISMATCH", "This operation does not belong to the fabrication job."); try { operation.complete(); } catch (IllegalStateException exception) { throw conflict("OPERATION_ALREADY_COMPLETED", "This operation is already completed."); } return response(job); }
    public Response assignMaterial(UUID id, MaterialInput input) { FabricationJob job = entity(id); ensureJobActive(job); if (job.getMaterials().stream().anyMatch(material -> material.isActive() && material.getMaterialType() == input.materialType() && material.getMaterialId().equals(input.materialId()))) throw conflict("MATERIAL_ALREADY_ASSIGNED", "This material is already assigned to the job."); BigDecimal reservedQuantity = reserveMaterial(job, input); job.addMaterial(new FabricationMaterial(job, input.materialType(), input.materialId(), reservedQuantity, trim(input.notes()))); job.getOrder().event("FABRICATION_MATERIAL_RESERVED", "Material reserved for fabrication job " + job.getJobNumber()); return response(job); }
    public Response cancel(UUID id) { FabricationJob job = entity(id); try { job.cancel(); } catch (IllegalStateException exception) { throw conflict("FABRICATION_NOT_CANCELLABLE", "Ready or cancelled fabrication jobs cannot be cancelled."); } for (FabricationMaterial material : job.getMaterials()) if (material.isActive()) { releaseMaterial(job, material); material.release(); } job.getOrder().event("FABRICATION_JOB_CANCELLED", "Fabrication job " + job.getJobNumber() + " cancelled and material reservations released"); return response(job); }
    private BigDecimal reserveMaterial(FabricationJob job, MaterialInput input) { return switch (input.materialType()) { case INVENTORY_ITEM -> { InventoryItem item = inventory.findByIdForUpdate(input.materialId()).orElseThrow(() -> notFound("FABRICATION_MATERIAL_NOT_FOUND", "Selected material was not found.")); ensureMaterialFree(input.materialType(), input.materialId()); BigDecimal quantity = input.quantityM2() == null ? item.getAvailableM2() : input.quantityM2(); reserveInventory(item, quantity, job); yield quantity; } case SLAB -> { var slab = slabs.findByIdForUpdate(input.materialId()).orElseThrow(() -> notFound("FABRICATION_MATERIAL_NOT_FOUND", "Selected material was not found.")); ensureMaterialFree(input.materialType(), input.materialId()); try { slab.allocateForFabrication(); } catch (IllegalStateException exception) { throw conflict("FABRICATION_MATERIAL_UNAVAILABLE", "Only an available or held slab can be assigned to fabrication."); } InventoryItem item = inventory.findByIdForUpdate(slab.getInventoryItem().getId()).orElseThrow(() -> notFound("FABRICATION_MATERIAL_NOT_FOUND", "Slab inventory was not found.")); reserveInventory(item, slab.getSurfaceAreaM2(), job); yield slab.getSurfaceAreaM2(); } case REMNANT -> { var remnant = remnants.findByIdForUpdate(input.materialId()).orElseThrow(() -> notFound("FABRICATION_MATERIAL_NOT_FOUND", "Selected material was not found.")); ensureMaterialFree(input.materialType(), input.materialId()); try { remnant.allocateForFabrication(); } catch (IllegalStateException exception) { throw conflict("FABRICATION_MATERIAL_UNAVAILABLE", "Only an available or held offcut can be assigned to fabrication."); } InventoryItem item = inventory.findByIdForUpdate(remnant.getParentSlab().getInventoryItem().getId()).orElseThrow(() -> notFound("FABRICATION_MATERIAL_NOT_FOUND", "Offcut inventory was not found.")); reserveInventory(item, remnant.getSurfaceAreaM2(), job); yield remnant.getSurfaceAreaM2(); } }; }
    private void releaseMaterial(FabricationJob job, FabricationMaterial material) { switch (material.getMaterialType()) { case INVENTORY_ITEM -> releaseInventoryReservation(inventory.findByIdForUpdate(material.getMaterialId()).orElseThrow(() -> notFound("FABRICATION_MATERIAL_NOT_FOUND", "Reserved inventory was not found.")), material.getReservedQuantityM2(), job); case SLAB -> { var slab = slabs.findByIdForUpdate(material.getMaterialId()).orElseThrow(() -> notFound("FABRICATION_MATERIAL_NOT_FOUND", "Reserved slab was not found.")); InventoryItem item = inventory.findByIdForUpdate(slab.getInventoryItem().getId()).orElseThrow(() -> notFound("FABRICATION_MATERIAL_NOT_FOUND", "Slab inventory was not found.")); releaseInventoryReservation(item, material.getReservedQuantityM2(), job); try { slab.releaseFabrication(); } catch (IllegalStateException exception) { throw conflict("FABRICATION_RESERVATION_MISMATCH", "The slab is no longer in fabrication allocation state."); } } case REMNANT -> { var remnant = remnants.findByIdForUpdate(material.getMaterialId()).orElseThrow(() -> notFound("FABRICATION_MATERIAL_NOT_FOUND", "Reserved offcut was not found.")); InventoryItem item = inventory.findByIdForUpdate(remnant.getParentSlab().getInventoryItem().getId()).orElseThrow(() -> notFound("FABRICATION_MATERIAL_NOT_FOUND", "Offcut inventory was not found.")); releaseInventoryReservation(item, material.getReservedQuantityM2(), job); try { remnant.releaseFabrication(); } catch (IllegalStateException exception) { throw conflict("FABRICATION_RESERVATION_MISMATCH", "The offcut is no longer in fabrication allocation state."); } } } }
    private void reserveInventory(InventoryItem item, BigDecimal quantity, FabricationJob job) { if (quantity.signum() <= 0) throw conflict("FABRICATION_STOCK_UNAVAILABLE", "The selected inventory position has no stock available for fabrication."); try { item.reserve(quantity); } catch (IllegalArgumentException exception) { throw conflict("FABRICATION_STOCK_UNAVAILABLE", "The selected inventory quantity is not available for fabrication."); } movements.save(new StockMovement(item, MovementType.FABRICATION_RESERVATION, quantity, "Fabrication material reserved", null, Instant.now(), job.getJobNumber(), null)); }
    private void releaseInventoryReservation(InventoryItem item, BigDecimal quantity, FabricationJob job) { try { item.releaseReservation(quantity); } catch (IllegalArgumentException exception) { throw conflict("FABRICATION_RESERVATION_MISMATCH", "The fabrication inventory reservation can no longer be released safely."); } movements.save(new StockMovement(item, MovementType.FABRICATION_RESERVATION_RELEASE, quantity, "Fabrication material reservation released", null, Instant.now(), job.getJobNumber(), null)); }
    private void consumeMaterials(FabricationJob job) { for (FabricationMaterial material : job.getMaterials()) if (material.isActive()) { switch (material.getMaterialType()) { case INVENTORY_ITEM -> consumeInventory(inventory.findByIdForUpdate(material.getMaterialId()).orElseThrow(() -> notFound("FABRICATION_MATERIAL_NOT_FOUND", "Reserved inventory was not found.")), material.getReservedQuantityM2(), job); case SLAB -> { var slab = slabs.findByIdForUpdate(material.getMaterialId()).orElseThrow(() -> notFound("FABRICATION_MATERIAL_NOT_FOUND", "Reserved slab was not found.")); consumeInventory(inventory.findByIdForUpdate(slab.getInventoryItem().getId()).orElseThrow(() -> notFound("FABRICATION_MATERIAL_NOT_FOUND", "Slab inventory was not found.")), material.getReservedQuantityM2(), job); try { slab.consumeForFabrication(); } catch (IllegalStateException exception) { throw conflict("FABRICATION_RESERVATION_MISMATCH", "The slab is no longer in fabrication allocation state."); } } case REMNANT -> { var remnant = remnants.findByIdForUpdate(material.getMaterialId()).orElseThrow(() -> notFound("FABRICATION_MATERIAL_NOT_FOUND", "Reserved offcut was not found.")); consumeInventory(inventory.findByIdForUpdate(remnant.getParentSlab().getInventoryItem().getId()).orElseThrow(() -> notFound("FABRICATION_MATERIAL_NOT_FOUND", "Offcut inventory was not found.")), material.getReservedQuantityM2(), job); try { remnant.consumeForFabrication(); } catch (IllegalStateException exception) { throw conflict("FABRICATION_RESERVATION_MISMATCH", "The offcut is no longer in fabrication allocation state."); } } } material.release(); } job.getOrder().event("FABRICATION_MATERIAL_CONSUMED", "Material consumed by fabrication job " + job.getJobNumber()); }
    private void consumeInventory(InventoryItem item, BigDecimal quantity, FabricationJob job) { try { item.deliverReserved(quantity); } catch (IllegalArgumentException exception) { throw conflict("FABRICATION_RESERVATION_MISMATCH", "The fabrication inventory reservation can no longer be consumed safely."); } movements.save(new StockMovement(item, MovementType.FABRICATION_CONSUMPTION, quantity, "Fabrication material consumed", null, Instant.now(), job.getJobNumber(), null)); }
    private void ensureMaterialFree(FabricationMaterialType type, UUID id) { if (materials.existsByMaterialTypeAndMaterialIdAndReleasedAtIsNull(type, id)) throw conflict("MATERIAL_ASSIGNED_TO_ANOTHER_JOB", "This physical material is already reserved for another fabrication job."); }
    private void ensureJobActive(FabricationJob job) { if (job.getStatus() == FabricationStatus.CANCELLED || job.getStatus() == FabricationStatus.READY || job.getOrder().getStatus() == OrderStatus.CANCELLED) throw conflict("FABRICATION_NOT_ACTIVE", "Materials and operations cannot be changed on this fabrication job."); }
    private FabricationJob entity(UUID id) { return jobs.findById(id).orElseThrow(() -> notFound("FABRICATION_JOB_NOT_FOUND", "Fabrication job was not found.")); }
    private Response response(FabricationJob job) { SalesOrder order = job.getOrder(); return new Response(job.getId(), job.getJobNumber(), order.getId(), order.getNumber(), order.getCustomer().getName(), order.getProject().getName(), job.getTitle(), job.getStatus(), job.getPriority(), job.getDueDate(), job.getMeasurementNotes(), job.getDrawingUrl(), job.getNotes(), job.getCreatedAt(), job.getReadyAt(), job.getOperations().stream().sorted(Comparator.comparingInt(FabricationOperation::getSequenceNo)).map(operation -> new Operation(operation.getId(), operation.getOperationType(), operation.getSequenceNo(), operation.getNotes(), operation.getStatus(), operation.getCompletedAt())).toList(), job.getMaterials().stream().map(this::material).toList()); }
    private Material material(FabricationMaterial material) { return switch (material.getMaterialType()) { case INVENTORY_ITEM -> { var item = inventory.findById(material.getMaterialId()).orElseThrow(); yield new Material(material.getId(), material.getMaterialType(), item.getId(), item.getVariant().getMaterial().getName(), item.getWarehouse().getName() + " / " + item.getLocation().getCode() + " · " + item.getAvailableM2() + " m² available", material.getReservedQuantityM2(), material.getReleasedAt(), material.getNotes()); } case SLAB -> { var slab = slabs.findById(material.getMaterialId()).orElseThrow(); yield new Material(material.getId(), material.getMaterialType(), slab.getId(), slab.getSlabNumber(), slab.getInventoryItem().getVariant().getMaterial().getName() + " · " + slab.getSurfaceAreaM2() + " m²", material.getReservedQuantityM2(), material.getReleasedAt(), material.getNotes()); } case REMNANT -> { var remnant = remnants.findById(material.getMaterialId()).orElseThrow(); yield new Material(material.getId(), material.getMaterialType(), remnant.getId(), remnant.getRemnantNumber(), remnant.getParentSlab().getInventoryItem().getVariant().getMaterial().getName() + " · " + remnant.getSurfaceAreaM2() + " m²", material.getReservedQuantityM2(), material.getReleasedAt(), material.getNotes()); } }; }
    private String nextNumber() { return "FAB-" + LocalDate.now().toString().replace("-", "") + "-" + UUID.randomUUID().toString().substring(0, 6).toUpperCase(Locale.ROOT); }
    private String trim(String value) { return value == null || value.isBlank() ? null : value.trim(); }
    private ApiException notFound(String code, String message) { return new ApiException(HttpStatus.NOT_FOUND, code, message); } private ApiException conflict(String code, String message) { return new ApiException(HttpStatus.CONFLICT, code, message); }
}
