package com.univmar.inventory.domain;

public enum MovementType {
    INITIAL_STOCK,
    PURCHASE_RECEIPT,
    ADJUSTMENT_IN,
    ADJUSTMENT_OUT,
    DAMAGE,
    RETURN,
    PHYSICAL_RECOUNT_IN,
    PHYSICAL_RECOUNT_OUT,
    LOCATION_TRANSFER_OUT,
    LOCATION_TRANSFER_IN,
    ORDER_RESERVATION,
    ORDER_RESERVATION_RELEASE,
    ORDER_DELIVERY,
    FABRICATION_RESERVATION,
    FABRICATION_RESERVATION_RELEASE,
    FABRICATION_CONSUMPTION
}
