import { useEffect, useMemo, useState } from "react";
import { ArrowLeft, Check, ClipboardList, Copy, CornerDownLeft, Grid3X3, MapPin, PackageCheck, Printer, QrCode, Search, ScanLine, Tag, X } from "lucide-react";
import { api, apiBaseUrl } from "../../shared/api/client";
import { Button } from "../../shared/ui";
import { useRouter } from "../../app/providers/router";

type TargetType = "INVENTORY_ITEM" | "SLAB";
type Label = { id: string; code: string; targetType: TargetType; targetId: string; qrImageUrl: string; scanUrl: string; createdAt: string };
type ScanResult = { code: string; targetType: TargetType; title: string; materialName: string; variantLabel: string; lotNumber?: string; bundleNumber?: string; warehouseName: string; locationCode: string; status: string; onHandM2?: number; availableM2?: number; reservedM2?: number; lengthMm?: number; widthMm?: number; thicknessMm?: number; surfaceAreaM2?: number; photoUrl?: string; relatedOrderNumber?: string; relatedProjectName?: string };
type Slab = { id: string; slabNumber: string; materialName: string; status: string; warehouseName: string; locationCode: string };
type Inventory = { id: string; materialName: string; thicknessMm: number; warehouse: { name: string }; location: { code: string }; lotNumber?: string; bundleNumber?: string };
type Page<T> = { content: T[] };
const amount = (value?: number) => value === undefined || value === null ? "—" : `${Number(value).toLocaleString(undefined, { maximumFractionDigits: 3 })} m²`;
const display = (value: string) => value.replaceAll("_", " ").toLowerCase().replace(/\b\w/g, letter => letter.toUpperCase());

export function ScanPage() {
  const { navigate } = useRouter(); const [code, setCode] = useState(""); const [result, setResult] = useState<ScanResult | null>(null); const [error, setError] = useState(""); const [loading, setLoading] = useState(false); const [labelsOpen, setLabelsOpen] = useState(false);
  useEffect(() => { const shared = new URLSearchParams(window.location.search).get("code"); if (shared) { setCode(shared); void lookup(shared); } }, []);
  function extractCode(value: string) { try { const url = new URL(value); return url.searchParams.get("code") ?? value; } catch { return value.trim(); } }
  async function lookup(raw = code) { const lookupCode = extractCode(raw); if (!lookupCode) return; setLoading(true); setError(""); setResult(null); try { const scanned = await api<ScanResult>(`/labels/scan/${encodeURIComponent(lookupCode)}`); setCode(lookupCode); setResult(scanned); } catch (cause) { setError((cause as Error).message); } finally { setLoading(false); } }
  return <section className="mx-auto max-w-4xl px-4 py-5 sm:px-7 sm:py-8"><header className="flex items-center justify-between gap-3 border-b border-[#d8ccc4] pb-5"><div><p className="text-[11px] font-semibold tracking-[0.16em] text-[#806f65]">WAREHOUSE MOBILE DESK</p><h1 className="mt-1 font-serif text-3xl">Scan a label</h1></div><button type="button" onClick={() => setLabelsOpen(true)} className="inline-flex h-10 items-center gap-2 rounded-md border border-[#c8a37f] bg-white px-3 text-sm font-semibold text-[#66412c] hover:bg-[#fff9f3]"><Printer size={16} /> Issue label</button></header><div className="mt-6 rounded-xl bg-[#160d09] p-4 text-white shadow-xl shadow-[#24120b]/15 sm:p-6"><div className="flex items-start gap-3"><div className="grid size-11 shrink-0 place-items-center rounded-md bg-[#d7a469] text-[#1d0e07]"><ScanLine size={23} /></div><div><p className="font-serif text-xl">Point a scanner, then confirm</p><p className="mt-1 text-sm text-white/65">Use a USB/Bluetooth scanner or paste the QR URL. The record opens with its live storage and reservation status.</p></div></div><form className="mt-5 flex gap-2" onSubmit={event => { event.preventDefault(); void lookup(); }}><label className="sr-only" htmlFor="label-code">QR label code</label><input id="label-code" autoFocus value={code} onChange={event => setCode(event.target.value)} placeholder="Scan or enter label code" className="h-12 min-w-0 flex-1 rounded-md border border-white/20 bg-white px-3 text-base text-black outline-none placeholder:text-[#8d7a70] focus:ring-2 focus:ring-[#e3bb8b]" /><button type="submit" disabled={loading || !code.trim()} className="grid size-12 shrink-0 place-items-center rounded-md bg-[#d7a469] text-[#1d0e07] hover:bg-[#e4ba87] disabled:opacity-60" aria-label="Find labelled record">{loading ? <span className="size-4 animate-spin rounded-full border-2 border-[#1d0e07] border-t-transparent" /> : <Search size={19} />}</button></form></div>{error && <div className="mt-5 rounded-lg border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700"><b>Label not found.</b> {error} Check that the complete QR code was scanned, then try again.</div>}{result && <ScanRecord result={result} onScanAnother={() => { setResult(null); setCode(""); }} />}{!result && !error && <div className="mt-7 grid gap-4 sm:grid-cols-3"><Hint icon={<QrCode size={19} />} title="Scan the code" detail="The label opens this internal scan page." /><Hint icon={<MapPin size={19} />} title="Confirm position" detail="See material, m², and warehouse location." /><Hint icon={<PackageCheck size={19} />} title="Handle correctly" detail="Check reservation before moving or cutting stock." /></div>}{labelsOpen && <LabelStudio onClose={() => setLabelsOpen(false)} onIssued={label => { setLabelsOpen(false); setCode(label.code); void lookup(label.code); }} />}</section>;
}

function ScanRecord({ result, onScanAnother }: { result: ScanResult; onScanAnother: () => void }) { const { navigate } = useRouter(); const slab = result.targetType === "SLAB"; return <article className="mt-6 overflow-hidden rounded-xl border border-[#d8ccc4] bg-white shadow-sm"><header className="flex flex-wrap items-start justify-between gap-4 border-b border-[#e8ddd6] bg-[#fffaf6] px-5 py-5"><div className="flex gap-3"><div className="grid size-11 place-items-center rounded-md bg-[#f0ddc8] text-[#774a30]">{slab ? <Grid3X3 size={21} /> : <Tag size={21} />}</div><div><p className="text-[11px] font-bold tracking-[0.13em] text-[#806f65]">{slab ? "INDIVIDUAL SLAB" : "INVENTORY LOT / BUNDLE"}</p><h2 className="mt-1 font-serif text-3xl">{result.title}</h2><p className="mt-1 text-sm text-[#786961]">{result.materialName} · {result.variantLabel}</p></div></div><span className="rounded-full bg-[#e6f4ec] px-3 py-1.5 text-xs font-bold text-emerald-800">{display(result.status)}</span></header><div className="grid gap-px bg-[#e8ddd6] sm:grid-cols-2 lg:grid-cols-4"><Cell title="Warehouse" value={result.warehouseName} /><Cell title="Position" value={result.locationCode} /><Cell title="Lot / bundle" value={[result.lotNumber && `Lot ${result.lotNumber}`, result.bundleNumber && `Bundle ${result.bundleNumber}`].filter(Boolean).join(" · ") || "Not assigned"} /><Cell title={slab ? "Physical surface" : "Available now"} value={slab ? amount(result.surfaceAreaM2) : amount(result.availableM2)} /></div>{slab && <div className="grid gap-px border-t border-[#e8ddd6] bg-[#e8ddd6] sm:grid-cols-3"><Cell title="Dimensions" value={`${result.lengthMm} × ${result.widthMm} mm`} /><Cell title="Thickness" value={`${result.thicknessMm} mm`} /><Cell title="Inventory availability" value={amount(result.availableM2)} /></div>}<div className="p-5"><div className="rounded-lg border border-[#e5dad3] bg-[#fdfbf9] p-4"><p className="text-[11px] font-bold tracking-[0.13em] text-[#806f65]">RESERVATION CHECK</p>{result.relatedOrderNumber ? <div className="mt-2"><p className="font-medium text-[#4b3328]">Reserved for {result.relatedOrderNumber}</p><p className="mt-1 text-sm text-[#786961]">Project: {result.relatedProjectName ?? "Not assigned"}. Do not move or cut this piece without the order team.</p></div> : <p className="mt-2 text-sm text-[#5f483c]">No exact order reservation is attached to this record.</p>}</div><div className="mt-5 flex flex-wrap gap-2"><Button onClick={onScanAnother}><ScanLine size={16} /> Scan another</Button><button type="button" onClick={() => navigate(slab ? "/slabs" : "/inventory")} className="inline-flex h-10 items-center gap-2 rounded-md border border-[#d8ccc4] px-3 text-sm font-medium hover:bg-[#faf7f5]"><ArrowLeft size={16} /> Open {slab ? "slabs" : "inventory"}</button></div></div></article>; }
function Cell({ title, value }: { title: string; value: string }) { return <div className="bg-white px-4 py-4"><p className="text-[10px] font-bold uppercase tracking-[0.12em] text-[#806f65]">{title}</p><p className="mt-1 text-sm font-medium">{value}</p></div>; }
function Hint({ icon, title, detail }: { icon: React.ReactNode; title: string; detail: string }) { return <div className="rounded-lg border border-[#d8ccc4] bg-white p-4"><div className="text-[#a4764d]">{icon}</div><p className="mt-3 font-medium">{title}</p><p className="mt-1 text-sm text-[#786961]">{detail}</p></div>; }

function LabelStudio({ onClose, onIssued }: { onClose: () => void; onIssued: (label: Label) => void }) {
  const [targetType, setTargetType] = useState<TargetType>("SLAB"); const [targetId, setTargetId] = useState(""); const [slabs, setSlabs] = useState<Slab[]>([]); const [inventory, setInventory] = useState<Inventory[]>([]); const [issued, setIssued] = useState<Label | null>(null); const [loading, setLoading] = useState(false); const [error, setError] = useState("");
  useEffect(() => { void Promise.all([api<Slab[]>("/slabs"), api<Page<Inventory>>("/inventory?size=100")]).then(([slabRecords, inventoryRecords]) => { setSlabs(slabRecords); setInventory(inventoryRecords.content); }).catch(cause => setError((cause as Error).message)); }, []);
  const records = useMemo(() => targetType === "SLAB" ? slabs.map(item => ({ id: item.id, title: `${item.slabNumber} · ${item.materialName}`, detail: `${item.warehouseName}/${item.locationCode} · ${display(item.status)}` })) : inventory.map(item => ({ id: item.id, title: `${item.materialName} · ${item.thicknessMm} mm`, detail: `${item.warehouse.name}/${item.location.code}${item.lotNumber ? ` · Lot ${item.lotNumber}` : ""}` })), [targetType, slabs, inventory]);
  async function issue() { if (!targetId) return; setLoading(true); setError(""); try { setIssued(await api<Label>("/labels", { method: "POST", body: JSON.stringify({ targetType, targetId }) })); } catch (cause) { setError((cause as Error).message); } finally { setLoading(false); } }
  async function copy() { if (issued) await navigator.clipboard.writeText(issued.scanUrl); }
  return <div className="fixed inset-0 z-50 flex justify-end bg-black/35"><aside className="h-full w-full max-w-md overflow-y-auto bg-[#fdfbf9] shadow-2xl"><header className="flex items-start justify-between border-b border-[#d8ccc4] px-5 py-5"><div><p className="text-[11px] font-bold tracking-[0.13em] text-[#806f65]">WAREHOUSE LABELS</p><h2 className="mt-1 font-serif text-2xl">Issue a QR label</h2></div><button type="button" onClick={onClose} className="rounded-md p-2 text-[#786961] hover:bg-[#f0e9e4]" aria-label="Close label panel"><X size={19} /></button></header><div className="p-5">{issued ? <div className="text-center"><img src={`${apiBaseUrl}${issued.qrImageUrl}`} alt="Generated warehouse QR label" className="mx-auto size-64 border border-[#d8ccc4] bg-white p-3" /><p className="mt-4 font-serif text-2xl">Label ready</p><p className="mt-2 break-all text-xs text-[#786961]">{issued.code}</p><div className="mt-5 grid gap-2"><button type="button" onClick={() => window.print()} className="inline-flex h-10 items-center justify-center gap-2 rounded-md bg-[#160d09] px-3 text-sm font-semibold text-white hover:bg-[#332019]"><Printer size={16} /> Print this label</button><button type="button" onClick={() => void copy()} className="inline-flex h-10 items-center justify-center gap-2 rounded-md border border-[#d8ccc4] px-3 text-sm font-semibold hover:bg-white"><Copy size={16} /> Copy scan link</button><button type="button" onClick={() => onIssued(issued)} className="inline-flex h-10 items-center justify-center gap-2 rounded-md border border-[#d8ccc4] px-3 text-sm font-semibold hover:bg-white"><Check size={16} /> Test label now</button></div></div> : <><p className="text-sm text-[#786961]">One stable QR label can be issued for each received inventory position or individual slab. Issuing again returns the same label.</p><div className="mt-5 grid grid-cols-2 gap-2"><Choice active={targetType === "SLAB"} onClick={() => { setTargetType("SLAB"); setTargetId(""); }} icon={<Grid3X3 size={18} />} label="Individual slab" /><Choice active={targetType === "INVENTORY_ITEM"} onClick={() => { setTargetType("INVENTORY_ITEM"); setTargetId(""); }} icon={<Tag size={18} />} label="Lot / bundle" /></div><label className="mt-5 block text-sm font-semibold">Record<select className="mt-1 h-11 w-full rounded-md border border-[#d8ccc4] bg-white px-3 text-sm outline-none focus:border-[#110703]" value={targetId} onChange={event => setTargetId(event.target.value)}><option value="">Select a record to label</option>{records.map(record => <option key={record.id} value={record.id}>{record.title} — {record.detail}</option>)}</select></label>{error && <p className="mt-4 rounded-md border border-red-200 bg-red-50 px-3 py-2 text-sm text-red-700">{error}</p>}<Button className="mt-5 w-full" loading={loading} disabled={!targetId} onClick={() => void issue()}><QrCode size={17} /> Generate QR label</Button></>}</div></aside></div>;
}
function Choice({ active, onClick, icon, label }: { active: boolean; onClick: () => void; icon: React.ReactNode; label: string }) { return <button type="button" onClick={onClick} className={`flex min-h-20 flex-col items-start justify-center rounded-md border px-3 text-left transition-colors ${active ? "border-[#8d5f41] bg-[#f7e9d9] text-[#573522]" : "border-[#d8ccc4] bg-white text-[#5f483c] hover:bg-[#faf7f5]"}`}>{icon}<span className="mt-2 text-sm font-semibold">{label}</span></button>; }
