package com.univmar.document.domain;

public enum DocumentType { GENERAL, RFQ_ATTACHMENT, CUSTOMER_DOCUMENT, PROJECT_PLAN, QUOTATION, PURCHASE_ORDER, INVOICE, DELIVERY_NOTE, TECHNICAL_DRAWING, IMAGE }
